// Generated by tools/build_source_materials.py
#define BEAM_KIND 1
// Clean native teleporter ink at texel centres, then interpolate explicitly.
// This preserves QRUNT63's four silhouettes under nearest/trilinear filtering.
float RunePixel(vec2 pixel,float index)
{
 pixel=clamp(pixel,vec2(0.0),vec2(31.0));
 vec4 c=texture(runeAtlas,(pixel+vec2(0.5,index*32.0+0.5))/vec2(32.0,128.0));
 return step(0.04,c.r-max(c.g,c.b))*c.a;
}
float Rune(vec2 uv,float index)
{
 if(any(lessThan(uv,vec2(0.0)))||any(greaterThan(uv,vec2(1.0))))return 0.0;
 index=mod(index,4.0);
 vec2 p=uv*32.0-0.5,b=floor(p),f=fract(p);
 return mix(mix(RunePixel(b,index),RunePixel(b+vec2(1,0),index),f.x),
            mix(RunePixel(b+vec2(0,1),index),RunePixel(b+vec2(1,1),index),f.x),f.y);
}
// Material-bound flecks rise with the energy; no particle actors or spawn loops.
float EnergyHash(float n){return fract(sin(n*127.1)*43758.5453);}
float EnergyNoise(vec2 p)
{
 vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);
 float n=i.x+i.y*57.0;
 return mix(mix(EnergyHash(n),EnergyHash(n+1.0),f.x),mix(EnergyHash(n+57.0),EnergyHash(n+58.0),f.x),f.y);
}
vec4 ProcessTexel()
{
 int state=int(texture(tex,vec2(0.5)).r*255.0+0.5);
 if(state==2)return vec4(0.0);
 float intensity,marks=0.0;
 float pull=clamp(float(state-5)/23.0,0.0,1.0);
 float height=pixelpos.y;
#if BEAM_KIND == 0
 float across=fract(vTexCoord.x)-0.5;
 if(abs(across)>.18)return vec4(0.0);
 float flow=height-timer*190.0;
 float warp=(sin(flow*.018)+.45*sin(flow*.051+1.7))*.006;
 float x=abs(across-warp)*(1.0+pull*6.0);
 // A coherent hot spine inside ragged, upward-flowing plasma filaments.
 float grain=EnergyNoise(vec2(across*85.0,flow*.045));
 float braid=.5+.5*sin(across*320.0+flow*.038+grain*4.0);
 intensity=1.08*exp(-x*x*2100.0);
 intensity+=exp(-x*x*420.0)*(.18+.62*grain)*(.40+.60*braid);
 intensity+=.16*exp(-x*x*65.0)*grain*grain;
 intensity*=1.0-smoothstep(.14,.18,abs(across));
 if(state<2 && abs(across)<.13)
 {
  float row=(height-timer*145.0)/190.0,cell=floor(row),v=fract(row);
  float lane=(EnergyHash(cell)*2.0-1.0)*.09;
  vec2 glyph=vec2((across-lane)/.034+.5,(v-.5)/.19+.5);
  if(EnergyHash(cell+71.0)>.48)marks+=Rune(glyph,cell)*.90;
  float sparkRow=(height-timer*240.0)/110.0,seed=floor(sparkRow);
  float sx=across-(EnergyHash(seed+14.0)*2.0-1.0)*.08;
  float sy=fract(sparkRow)-.5;
  marks+=1.2*exp(-sx*sx*130000.0-sy*sy*900.0);
 }
#else
 // Round helix inside the unchanged polygonal carrier. Renderer axes are X,Z,Y.
 vec3 hit=pixelpos.xyz,eye=uCameraPos.xyz;
 vec2 center=hit.x>6000.0?vec2(10624.0,-192.0):vec2(130.0,-382.0);
 vec3 ray=normalize(hit-eye);vec2 q=eye.xz-center;
 float a=dot(ray.xz,ray.xz),b=dot(q,ray.xz);
 float radius=430.0*(1.0-pull*pull*.97);
 float disc=b*b-a*(dot(q,q)-radius*radius);
 if(disc<=0.0 || a<.00001)return vec4(0.0);
 float side=dot(hit.xz-center,ray.xz)<0.0?-1.0:1.0;
 float t=(-b+side*sqrt(disc))/a;
 if(t<0.0)return vec4(0.0);
 vec3 surface=eye+ray*t;vec2 d=surface.xz-center;height=surface.y;
 float turn=atan(d.y,d.x)/6.2831853;
 float phase=turn+height/(1100.0-600.0*pull)+pull*1.5;
 if(state<2)phase-=timer*.06;
 float coverage=1.0-smoothstep(.10,.16,abs(fract(phase)-.5));
 if(coverage<=0.0)return vec4(0.0);
 float flow=height-timer*180.0;
 float grain=EnergyNoise(vec2(d.x*.022+d.y*.016,flow*.033));
 float warp=(grain-.5)*.011+sin(flow*.027+turn*18.84956)*.003;
 float band=fract(phase-warp)-.5,edge=abs(band);
 float aa=clamp(fwidth(phase),.0004,.006);
 float width=.00006+aa*aa;
 intensity=(.55+.70*grain)*exp(-edge*edge/width);
 float filaments=.5+.5*sin(band*760.0+flow*.042+grain*5.0);
 intensity+=.58*exp(-edge*edge*950.0)*filaments*grain;
 intensity+=.12*exp(-edge*edge*140.0)*grain*grain;
 intensity*=coverage;
 if(state<2 && edge<.06)
 {
  float row=(height-timer*165.0)/260.0,cell=floor(row),v=fract(row);
  if(EnergyHash(cell+31.0)>.55)marks+=Rune(vec2(band/.022+.5,(v-.5)/.14+.5),cell)*.85;
  float sy=fract((height-timer*260.0)/125.0)-.5;
  marks+=1.25*exp(-band*band*180000.0-sy*sy*1100.0);
 }
#endif
 vec3 color=mix(vec3(1.0,.20,.008),vec3(1.0,.82,.32),pow(clamp(intensity,0.0,1.0),3.0));
 // Preserve the target's readability; ornament follows the same attenuation.
 float nearBoss=1.0-smoothstep(280.0,470.0,abs(height-3968.0));
#if BEAM_KIND == 0
 float clear=mix(1.0,.10,nearBoss);
#else
 float clear=mix(1.0,.35,nearBoss);
#endif
 intensity*=clear;marks*=clear;
 if(state==1){intensity*=mix(.65,.40,nearBoss);marks*=.60;}
 else if(state>=3)
 {
#if BEAM_KIND == 0
  intensity*=state==3?.16:.28;
#else
  intensity*=.035;
#endif
  if(state>=5)
  {
   float extent=2600.0*(1.0-pull*pull);
   intensity*=1.0-smoothstep(extent,extent+80.0,abs(height-3968.0));
  }
 }
 return vec4(color*intensity+vec3(1.0,.58,.10)*marks,1.0);
}
