// Generated by tools/build_source_materials.py
// Clean native teleporter ink at texel centres, then interpolate explicitly.
// This preserves QRUNT63's four silhouettes under nearest/trilinear filtering.
float RunePixel(vec2 pixel,float index)
{
 pixel=clamp(pixel,vec2(0.0),vec2(31.0));
 vec4 c=texture(runeAtlas,(pixel+vec2(0.5,index*32.0+0.5))/vec2(32.0,128.0));
 return step(0.04,c.r-max(c.g,c.b))*c.a;
}
float Rune(vec2 uv,float index)
{
 if(any(lessThan(uv,vec2(0.0)))||any(greaterThan(uv,vec2(1.0))))return 0.0;
 index=mod(index,4.0);
 vec2 p=uv*32.0-0.5,b=floor(p),f=fract(p);
 return mix(mix(RunePixel(b,index),RunePixel(b+vec2(1,0),index),f.x),
            mix(RunePixel(b+vec2(0,1),index),RunePixel(b+vec2(1,1),index),f.x),f.y);
}
// Rune() is prepended from source-rune.glsl by the material builder.
float Ring(float r,float target,float width)
{
 return 1.0-smoothstep(width,width+max(fwidth(r),0.002),abs(r-target));
}
float Hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
// Stable, smoothly interpolated density for the short black collapse cloud.
float SmokeHash(vec2 cell)
{
 uint h=uint(int(cell.x))*0x8da6b343u ^ uint(int(cell.y))*0xd8163841u;
 h=(h^(h>>16u))*0x7feb352du;h=(h^(h>>15u))*0x846ca68bu;
 return float((h^(h>>16u))&0x00ffffffu)/16777216.0;
}
float SmokeNoise(vec2 p)
{
 vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);
 return mix(mix(SmokeHash(i),SmokeHash(i+vec2(1,0)),f.x),
            mix(SmokeHash(i+vec2(0,1)),SmokeHash(i+vec2(1,1)),f.x),f.y);
}
vec4 ProcessTexel()
{
 int kind=int(texture(sourceKind,vec2(.5)).r*255.0+.5);
 vec2 p=(vTexCoord.st-0.5)*2.0;float r=length(p);
 if(kind==25)
 {
  if(r>.98)return vec4(0.0);
  vec2 flow=vec2(timer*.23,-timer*.17);
  float billow=SmokeNoise(p*3.1+flow);
  float curl=SmokeNoise(p*7.3-flow*.7);
  float edge=1.0-smoothstep(.48,.96,r+(billow-.5)*.28);
  float density=edge*(.58+.28*billow+.14*curl);
  // Double optical thickness while preserving soft, detailed cloud edges.
  density=1.0-(1.0-density)*(1.0-density);
  // True translucent near-black smoke; additive black would be invisible.
  return vec4(vec3(.008,.006,.005)*(.55+.45*curl),density);
 }
 float a=atan(p.y,p.x), turn=(a+3.14159265)/6.2831853;
 float ink=0.0,heat=0.0;vec3 gold=vec3(1.0,0.37,0.035);
 if(kind == 0 || kind == 1) {
 // Keep the original horned skull and its geometry. Remove only its old outer
 // border, now represented by independently moving native rune arcs.
 vec4 c=getTexel(vTexCoord.st);
 float v=max(c.r,max(c.g,c.b))*c.a;
 ink=(0.25*v+0.75*v*v)*(1.0-smoothstep(0.91,0.98,r));
 gold=mix(vec3(1.0,0.28,0.015),vec3(1.0,0.58,0.08),clamp(c.g,0.0,1.0));
 if(kind == 1) {
 float crack=abs(sin(a*3.0+r*5.0+sin(r*31.0)*0.16));
 float broken=(1.0-smoothstep(0.012,0.045,crack))*smoothstep(0.15,0.3,r)*(1.0-smoothstep(0.84,0.94,r));
 ink+=broken*(0.55+0.1*sin(timer*4.0));heat=broken*0.25;
 }
 } else if(kind == 2 || kind == 3 || kind == 4) {
 float section=fract(turn*6.0);
 float mask=1.0;
 if(kind == 3) {
 mask=smoothstep(0.06,0.10,section)*(1.0-smoothstep(0.90,0.94,section));
 }
 float glyphTurn=turn*24.0;float glyphIndex=floor(glyphTurn);
 vec2 uv=vec2((fract(glyphTurn)-0.5)*1.30+0.5,(r-0.805)/0.115);
 float glyph=Rune(uv,glyphIndex);
 if(kind == 4) {
 glyph*=mod(glyphIndex,7.0)<1.0?0.08:1.0;
 }
 ink=(Ring(r,0.795,0.0025)+Ring(r,0.930,0.0035)+glyph*1.1)*mask;
 ink+=0.18*exp(-abs(r-0.93)*85.0)*mask;
 } else if(kind == 5) {
 // A small energy heart. Fullbright detail is restricted to this target.
 float core=exp(-r*r*32.0);
 float halo=0.20*exp(-r*r*5.0);
 ink=core+halo+Ring(r,0.43,0.015)*0.6+Ring(r,0.61,0.008)*0.3;
 heat=core;gold=vec3(1.0,0.52,0.08);
 } else if(kind == 6) {
 float rough=0.34+0.025*sin(a*7.0)+0.02*sin(a*13.0);
 float rock=1.0-smoothstep(rough,rough+0.025,r);
 float veins=pow(max(0.0,sin(p.x*21.0+sin(p.y*14.0))),14.0)*rock;
 ink=rock*(0.14+0.13*Hash(floor(p*22.0)))+veins*0.7;
 ink+=Ring(r,0.48,0.012)*0.8+Ring(r,0.91,0.008)*0.8;
 ink+=Rune(vec2(fract(turn*12.0),(r-0.64)/0.19),floor(turn*12.0));
 heat=veins*0.3;
 } else if(kind == 7) {
 ink=Ring(r,0.60,0.013)+Ring(r,0.83,0.006)*0.4;
 ink*=0.8+0.2*sin(a*6.0);
 } else if(kind == 8) {
 float slice=floor(turn*7.0);
 float chip=1.0-smoothstep(0.05,0.11,length(vec2((fract(turn*7.0)-0.5)*0.8,r-0.62)));
 ink=chip*(0.25+0.55*Hash(vec2(slice,2.0)));
 ink+=Rune(vec2(fract(turn*7.0),(r-0.77)/0.12),slice)*0.45;
 } else if(kind == 9) {
 ink=exp(-p.y*p.y*70.0)*(1.0-smoothstep(0.88,1.0,abs(p.x)));
 heat=ink*0.45;
 } else if(kind == 10) {
 float count=turn*13.0;
 float radius=0.82+0.08*sin(floor(count)*7.0);
 ink=Rune(vec2((fract(count)-0.5)*2.8+0.5,(r-radius)/0.065),floor(count));
 } else if(kind == 12) {
 // A thin branching bolt. Its silhouette changes; its brightness stays steady.
 float stepTime=floor(timer*12.0);
 float x=(p.x+1.0)*0.5;
 float node=x*14.0, cell=floor(node), f=fract(node);
 float jag=mix(Hash(vec2(cell,stepTime)),Hash(vec2(cell+1.0,stepTime)),f)-0.5;
 float path=jag*1.2*sin(x*3.14159265);
 float dist=abs(p.y-path);
 float bolt=exp(-dist*dist*380.0)+0.35*exp(-dist*dist*40.0);
 float branch=path+(x-0.42)*1.7;
 bolt+=0.55*exp(-pow(abs(p.y-branch),2.0)*2400.0)*smoothstep(0.40,0.45,x)*(1.0-smoothstep(0.67,0.75,x));
 return vec4(vec3(1.0,0.72,0.30)*bolt*(1.0-smoothstep(0.95,1.0,abs(p.x))),1.0);
 } else if(kind == 13 || kind == 16 || kind == 17) {
 // Reject the empty majority of each large ceiling quad before atlas reads.
 if(r<.60 || r>.98 || abs(a)>.35)discard;
 // One eighth of a horizontal ring, using the shaft's native QROCK3 stone.
 float ang=abs(a);
 float shape=smoothstep(0.63,0.65,r)*(1.0-smoothstep(0.94,0.96,r));
 shape*=1.0-smoothstep(0.30,0.34,ang);
 if(shape<=.001)discard; // Empty carrier pixels must never write depth.
 vec3 stone=texture(stoneAtlas,fract(vTexCoord.st*3.0)).rgb*0.48;
 float glyph=Rune(vec2(a/0.38+0.5,(r-0.69)/0.20),2.0);
 float rim=Ring(r,0.67,0.004)+Ring(r,0.93,0.004);
 float strength=0.18;
 if(kind == 16) {
 strength=1.0;
 } else if(kind == 17) {
 strength=0.0;
 }
 return vec4(stone+vec3(1.0,0.32,0.02)*(glyph+rim*0.45)*strength,shape);
 } else if(kind == 14) {
 if(r<.70 || r>.98 || abs(a)>.50)return vec4(0.0);
 float edge=abs(a);
 float mask=1.0-smoothstep(0.43,0.49,edge);
 float glyphTurn=turn*24.0;
 float glyph=Rune(vec2((fract(glyphTurn)-0.5)*1.30+0.5,(r-0.805)/0.115),floor(glyphTurn));
 ink=(Ring(r,0.795,0.003)+Ring(r,0.930,0.004)+glyph*1.1)*mask;
 heat=0.35;
 } else if(kind == 15) {
 vec4 c=getTexel(vTexCoord.st);
 float mask=max(c.r,max(c.g,c.b))*c.a*(1.0-smoothstep(0.91,0.98,r));
 return vec4(vec3(0.014,0.008,0.003),clamp(mask*3.0,0.0,1.0));
 } else if(kind == 18) {
 // An opaque black heart with a narrow hot rim; translucency preserves the void.
 float disc=1.0-smoothstep(0.66,0.69,r);
 float rim=exp(-pow((r-0.69)*65.0,2.0));
 float haze=exp(-pow((r-0.71)*12.0,2.0))*.22;
 return vec4(vec3(1.0,.34,.018)*(rim+haze),max(disc,rim+haze));
 } else if(kind == 19) {
 float spiral=pow(max(0.0,sin(a*3.0+r*24.0)),5.0);
 ink=(Ring(r,.62,.025)*.75+spiral*exp(-pow((r-.65)*6.0,2.0)));
 heat=spiral*.7;
 } else if(kind >= 20 && kind <= 23) {
 ink=Rune(vTexCoord.st,float(kind-20))*1.3;heat=.35;
 } else if(kind == 24) {
 float star=exp(-abs(p.x)*150.0)*exp(-abs(p.y)*4.0)+exp(-abs(p.y)*150.0)*exp(-abs(p.x)*4.0);
 return vec4(vec3(1.0,.93,.73)*(exp(-r*r*65.0)+star*.8+exp(-r*r*6.0)*.10),1.0);
 } else if(kind == 11) {
 // Broad, quiet amber light from the seal's centre, with no hard outer disc.
 // This is separate from the compact heart so attacks retain their telegraph.
 ink=0.32*exp(-r*r*3.0)+0.15*exp(-r*r*28.0);
 ink*=1.0-smoothstep(0.80,1.0,r);
 gold=vec3(1.0,0.40,0.035);
 }
 ink*=1.0-smoothstep(0.975,1.0,r);
 vec3 col=mix(gold,vec3(1.0,0.91,0.55),clamp(heat,0.0,1.0));
 return vec4(col*min(1.0,ink),1.0);
}
