// Generated by tools/build_source_materials.py
#define BEAM_KIND 2
#define BEAM_STATE 17
vec4 ProcessTexel()
{
 float intensity;
 float pull=clamp(float(BEAM_STATE-5)/23.0,0.0,1.0);
 float height=pixelpos.y;
#if BEAM_KIND == 0
 // Compress the existing core without changing its crossed wall geometry.
 float x=abs(fract(vTexCoord.x)-0.5)*(1.0+pull*6.0);
 intensity=1.25*exp(-x*x*900.0)+0.24*exp(-x*x*110.0)+0.045*exp(-x*x*18.0);
#else
 // Round the helix inside the unchanged polygonal carrier with a ray/cylinder
 // intersection. Renderer axes are X,Z,Y. Each stacked room has its own centre.
 vec3 hit=pixelpos.xyz,eye=uCameraPos.xyz;
 vec2 center=hit.x>6000.0?vec2(10624.0,-192.0):vec2(130.0,-382.0);
 vec3 ray=normalize(hit-eye);
 vec2 q=eye.xz-center;
 float a=dot(ray.xz,ray.xz),b=dot(q,ray.xz);
 float radius=430.0*(1.0-pull*pull*.97);
 float disc=b*b-a*(dot(q,q)-radius*radius);
 if(disc<=0.0 || a<0.00001)return vec4(0.0);
 float side=dot(hit.xz-center,ray.xz)<0.0?-1.0:1.0;
 float t=(-b+side*sqrt(disc))/a;
 if(t<0.0)return vec4(0.0);
 vec3 surface=eye+ray*t;
 vec2 d=surface.xz-center;
 height=surface.y;
 float phase=atan(d.y,d.x)/6.2831853+height/(1100.0-600.0*pull)+pull*1.5;
#if BEAM_STATE < 2
 phase-=timer*0.06;
#endif
 float edge=abs(fract(phase)-0.5);
 // atan's branch cut is not a wide beam; cap its discontinuous derivative.
 float aa=clamp(fwidth(phase),0.0004,0.006);
 intensity=1.25*exp(-edge*edge/(0.000035+aa*aa));
 intensity+=0.35*exp(-edge*edge*1200.0)+0.075*exp(-edge*edge*150.0);
#endif
 vec3 color=mix(vec3(1.0,0.23,0.012),vec3(1.0,0.85,0.39),pow(clamp(intensity,0.0,1.0),3.0));
 // Keep the seal legible even with the shield closed. Fade over its full
 // height and return smoothly to the original beam above and below it.
 float nearBoss=1.0-smoothstep(280.0,470.0,abs(height-3968.0));
#if BEAM_KIND == 0
 intensity*=mix(1.0,0.10,nearBoss);
#else
 intensity*=mix(1.0,0.35,nearBoss);
#endif
#if BEAM_STATE == 1
 // Opening the real shield makes the target still clearer.
 intensity*=mix(0.65,0.40,nearBoss);
#elif BEAM_STATE == 2
 intensity=0.0;
#elif BEAM_STATE >= 3
 // Both beam ends and the helix contract towards the seal before the collapse.
#if BEAM_KIND == 0
 intensity*=BEAM_STATE==3?0.16:0.28;
#else
 intensity*=0.035;
#endif
#if BEAM_STATE >= 5
 float extent=2600.0*(1.0-pull*pull);
 intensity*=1.0-smoothstep(extent,extent+80.0,abs(height-3968.0));
#endif
#endif
 return vec4(color*intensity,1.0);
}
