// Generated by tools/build_source_materials.py
#define BEAM_KIND 2
#define BEAM_STATE 1
vec4 ProcessTexel()
{
 vec4 c=getTexel(vTexCoord.st);
 float intensity;
#if BEAM_KIND == 0
 // Compress the existing core without changing its crossed wall geometry.
 float x=abs(fract(vTexCoord.x)-0.5);
 intensity=exp(-x*x*720.0)+0.045*exp(-x*x*65.0);
#else
 // A continuous world-space helix avoids the old front/back texture seams.
 // Renderer axes are X,Z,Y; undo the stacked-room XY displacement.
 vec2 xy=pixelpos.xz;
 if(xy.x>6000.0)xy-=vec2(10496.0,128.0);
 vec2 d=xy-vec2(128.0,-320.0);
 float phase=atan(d.y,d.x)/6.2831853+pixelpos.y/1100.0-timer*0.06;
 float edge=abs(fract(phase)-0.5);
 intensity=1.8*exp(-edge*edge*18000.0)+0.30*exp(-edge*edge*1500.0);
#endif
 vec3 color=mix(vec3(1.0,0.30,0.025),vec3(1.0,0.82,0.35),pow(clamp(intensity,0.0,1.0),3.0));
#if BEAM_STATE == 1
 // The target silhouette is unobscured while the actual shield is open.
 float nearBoss=1.0-smoothstep(420.0,900.0,abs(pixelpos.y-3904.0));
 intensity*=mix(0.65,0.12,nearBoss);
#elif BEAM_STATE == 2
 intensity=0.0;
#endif
 return vec4(color*intensity,c.a);
}
