// Generated by tools/build_source_materials.py
#define SOURCE_KIND 2
// Engine-native glyph atlas: exactly the campaign's nine RUNE patches.
float Rune(vec2 uv,float index)
{
 if(any(lessThan(uv,vec2(0)))||any(greaterThan(uv,vec2(1))))return 0.0;
 // Odd-numbered patches are the lit red signs; even ones are their unlit
 // switches. Red chroma separates the original sign from its grey stone tile.
 vec4 c=texture(runeAtlas,vec2((mod(index,5.0)*2.0+uv.x)/9.0,uv.y));
 return smoothstep(0.05,0.38,c.r-max(c.g,c.b))*c.a;
}
float Ring(float r,float target,float width)
{
 return 1.0-smoothstep(width,width+max(fwidth(r),0.002),abs(r-target));
}
float Hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
vec4 ProcessTexel()
{
 vec2 p=(vTexCoord.st-0.5)*2.0;float r=length(p);
 float a=atan(p.y,p.x), turn=(a+3.14159265)/6.2831853;
 float ink=0.0,heat=0.0;vec3 gold=vec3(1.0,0.37,0.035);
#if SOURCE_KIND == 0 || SOURCE_KIND == 1
 // Keep the original horned skull and its geometry. Remove only its old outer
 // border, now represented by independently moving native rune arcs.
 vec4 c=getTexel(vTexCoord.st);
 float v=max(c.r,max(c.g,c.b))*c.a;
 ink=v*(1.0-smoothstep(0.91,0.98,r));
 gold=mix(vec3(1.0,0.28,0.015),vec3(1.0,0.58,0.08),clamp(c.g,0.0,1.0));
#if SOURCE_KIND == 1
 float crack=abs(sin(a*3.0+r*5.0+sin(r*31.0)*0.16));
 float broken=(1.0-smoothstep(0.012,0.045,crack))*smoothstep(0.15,0.3,r)*(1.0-smoothstep(0.84,0.94,r));
 ink+=broken*(0.55+0.1*sin(timer*4.0));heat=broken*0.25;
#endif
#elif SOURCE_KIND == 2 || SOURCE_KIND == 3 || SOURCE_KIND == 4
 float section=fract(turn*6.0);
 float mask=1.0;
#if SOURCE_KIND == 3
 mask=smoothstep(0.06,0.10,section)*(1.0-smoothstep(0.90,0.94,section));
#endif
 float glyphTurn=turn*24.0;float glyphIndex=floor(glyphTurn);
 vec2 uv=vec2((fract(glyphTurn)-0.5)*1.30+0.5,(r-0.805)/0.115);
 float glyph=Rune(uv,glyphIndex);
#if SOURCE_KIND == 4
 glyph*=mod(glyphIndex,7.0)<1.0?0.08:1.0;
#endif
 ink=(Ring(r,0.795,0.0025)+Ring(r,0.930,0.0035)+glyph*1.1)*mask;
 ink+=0.06*exp(-abs(r-0.93)*85.0)*mask;
#elif SOURCE_KIND == 5
 // A small energy heart. Fullbright detail is restricted to this target.
 float core=exp(-r*r*32.0);
 float halo=0.20*exp(-r*r*5.0);
 ink=core+halo+Ring(r,0.43,0.015)*0.6+Ring(r,0.61,0.008)*0.3;
 heat=core;gold=vec3(1.0,0.52,0.08);
#elif SOURCE_KIND == 6
 float rough=0.34+0.025*sin(a*7.0)+0.02*sin(a*13.0);
 float rock=1.0-smoothstep(rough,rough+0.025,r);
 float veins=pow(max(0.0,sin(p.x*21.0+sin(p.y*14.0))),14.0)*rock;
 ink=rock*(0.14+0.13*Hash(floor(p*22.0)))+veins*0.7;
 ink+=Ring(r,0.48,0.012)*0.8+Ring(r,0.91,0.008)*0.8;
 ink+=Rune(vec2(fract(turn*12.0),(r-0.64)/0.19),floor(turn*12.0));
 heat=veins*0.3;
#elif SOURCE_KIND == 7
 ink=Ring(r,0.60,0.013)+Ring(r,0.83,0.006)*0.4;
 ink*=0.8+0.2*sin(a*6.0);
#elif SOURCE_KIND == 8
 float slice=floor(turn*7.0);
 float chip=1.0-smoothstep(0.05,0.11,length(vec2((fract(turn*7.0)-0.5)*0.8,r-0.62)));
 ink=chip*(0.25+0.55*Hash(vec2(slice,2.0)));
 ink+=Rune(vec2(fract(turn*7.0),(r-0.77)/0.12),slice)*0.45;
#elif SOURCE_KIND == 9
 ink=exp(-p.y*p.y*70.0)*(1.0-smoothstep(0.88,1.0,abs(p.x)));
 heat=ink*0.45;
#elif SOURCE_KIND == 10
 float count=turn*13.0;
 float radius=0.82+0.08*sin(floor(count)*7.0);
 ink=Rune(vec2((fract(count)-0.5)*2.8+0.5,(r-radius)/0.065),floor(count));
#endif
 ink*=1.0-smoothstep(0.975,1.0,r);
 vec3 col=mix(gold,vec3(1.0,0.91,0.55),clamp(heat,0.0,1.0));
 return vec4(col*min(1.0,ink),1.0);
}
