///////////////////////////////////////
//Viper attack craft
///////////////////////////////////////

class DecorationShip : Actor
{
    Default
    {
    Radius 8;
    Height 6;
    Speed 6;
    Damage 3;
    SeeSound "viper/flyby";
    PROJECTILE;
    +DONTSPLASH;
    -ACTIVATEIMPACT;
    +NoGravity;
    +ACTIVATEPCROSS;
    }
    States
    {
    Spawn:
        MDLS A 1;
        MDLS A 0 A_SpawnItemEx("DecorationShip_Steam", -32, -5, -1);
        MDLS A 0 A_SpawnItemEx("DecorationShip_Steam", -32, 5, -1);
        Loop;
    Death:
        MDLS A 4;
        Stop;

    }
}

class DecorationShip_Steam : Actor
{
    Default
    {
    +MISSILE;
    +NOBLOCKMAP;
    +NOGRAVITY;
    +FORCEXYBILLBOARD;
    Radius 1;
    Height 1;
    RenderStyle "Add";
    Alpha 0.2;
    Scale 0.2;
    }
    States
    {
    Spawn:
        SSST A 0;
        SSST AAAA 1 BRIGHT A_FadeIn(0.2);
        SSST A 1 BRIGHT A_FadeOut;
        Wait;

    }
}

class DecorationStation : Actor
{
    Default
    {
    Height 64;
    +FLOORCLIP;
    +NOGRAVITY;
    }
    States
    {
    Spawn:
        MDLS A -1;
        Loop;

    }
}

class DecorationUT1 : DecorationStation
{

}
class DecorationUT2 : DecorationStation
{

}
