/////////////////////////
//	GREEN BEAM		   //
//		AND			   //
//		RED BEAM	   //
// Based on SKYBEAM by //
//		Tormentor667   //
/////////////////////////

// Used in STR09
class GREENBEAM_Projectile : Actor
{
    Default
    {
    +CLIENTSIDEONLY;
    Height 32;
    Radius 32;
    Mass 0;
    +Missile;
    +Nogravity;
    RenderStyle "Add";
    XScale 2.0;
    Alpha 0.8;
    }
    States
    {
    Spawn:
        SAWP A 60 Bright;
    Death:
        SAWP A 2 Bright A_FadeOut;
        Wait;

    }
}

class GREENBEAM_ProjectileSmall : GREENBEAM_Projectile
{
    Default
    {
    XScale 0.08;
    YScale 0.08;
    Alpha 0.6;
    }
}

class GREENBEAM : Thunder_Generator
{
    Default
    {
    //$Category Stronghold_SFX
    XScale 1.5;
    YScale 4.0;
    Alpha 0.01;
    }
    States
    {
    Spawn:
    Active:
        SKBM A 1 Bright A_SpawnItemEx("GREENBEAM_ProjectileSmall", random(-32,32), random(-32,32), 0, 0, 0, random(5,8));
        Loop;
    Inactive:
        TNT1 A -1;
        Loop;

    }
}

class REDBEAM_Projectile : GREENBEAM_Projectile
{
    States
    {
    Spawn:
        SAWS ABABABABABABABABABAB 3 Bright;
    Death:
        SAWS AB 2 Bright A_FadeOut;
        Loop;

    }
}

class REDBEAM : GREENBEAM
{
    Default
    {
    //$Category Stronghold_SFX
    }
    States
    {
    Spawn:
    Active:
        SKBM A 1 Bright A_SpawnItemEx("REDBEAM_ProjectileSmall", random(-32,32), random(-32,32), 0, 0, 0, random(5,8));
        Loop;

    }
}

class REDBEAM_ProjectileSmall : REDBEAM_Projectile
{
    Default
    {
    XScale 0.25;
    YScale 0.25;
    Alpha 0.6;
    }
}
