////////////////////////////////////////////////////////////////
//
// Particle effects used in splashes definitions
//
////////////////////////////////////////////////////////////////

class LavaParticle : Actor
{
    Default
    {
    +BLOODLESSIMPACT;
    +BRIGHT;
    +CANNOTPUSH;
    +DONTSPLASH;
    +DROPOFF;
    +FORCEXYBILLBOARD;
    BounceType "Hexen";
    +MISSILE;
    +NOBLOCKMAP;
    +NOTELEPORT;
    +PAINLESS;
    +RIPPER;
    Radius 1;
    Height 2;
    Gravity 0.25;
    Scale 0.04;
    BounceFactor .5;
    WallBounceFactor .5;
    }
    States
    {
    Spawn:
        PART A 0 A_JumpIf(waterlevel > 0, 2);
        PART A 1 BRIGHT A_FadeOut(0.05);
        loop;
        TNT1 A 0;
        stop;

    }
}

class SlimeParticle : LavaParticle
{
    States
    {
    Spawn:
        PART B 0;
        PART B 0 A_JumpIf(waterlevel > 0, 2);
        PART B 1 BRIGHT A_FadeOut(0.05);
        loop;
        TNT1 A 0;
        stop;

    }
}

////////////////////////////////////////////////////////////////
//
// Lava splashes
//
////////////////////////////////////////////////////////////////

class LavaSmoke2 : Actor
{
    Default
    {
    +DONTSPLASH;
    +FORCEXYBILLBOARD;
    +NOBLOCKMAP;
    +NOCLIP;
    +NOGRAVITY;
    Renderstyle "Translucent";
    Alpha 0.75;
    Translation "80:111 = 104:111";
    Scale 0.76;
    }
    States
    {
    Spawn:
        SMOK A 0;
        SMOK "ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]]" 1 Bright A_FadeOut(0.025);
        stop;

    }
}

class LavaSplash1_Base : LavaSplash
{
    Default
    {
    +FORCEYBILLBOARD;
    Renderstyle "Translucent";
    Alpha 0.5;
    //Translation "224:231 = [47, 0, 0]:[199, 71, 0]", "161:167 = [47, 0, 0]:[199, 71, 0]"
    }
    States
    {
    Spawn:
        LVAS A 0;
        LVAS AAAAAAAA 0 A_SpawnItemEx("LavaParticle", 0, 0, 0, random(-1, 1), random(-1, 1), random(3, 4), 0, 0, 160);
        goto Super::Spawn;

    }
}

class LavaSplash1_Small : LavaSplash1_Base
{
    Default
    {
    Scale 0.4;
    }
}

////////////////////////////////////////////////////////////////
//
// Sludge splashes
//
////////////////////////////////////////////////////////////////

class NukageSmoke : LavaSmoke2
{
    Default
    {
    Renderstyle "Add";
    }
    States
    {
    Spawn:
        SMOK A 0;
        SMOK "ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]" 1 Bright A_FadeOut(0.02);
        stop;

    }
}

class NukeSplash1_Base : SludgeSplash
{
    Default
    {
    +FORCEYBILLBOARD;
    Translation "112:127 = [0, 16, 0]:[118, 159, 1]";
    Renderstyle "Translucent";
    Alpha 0.5;
    }
    States
    {
    Spawn:
        SLDG E 0;
        SLDG EEEEEEEE 0 A_SpawnItemEx("SlimeParticle", 0, 0, 0, random(-1, 1), random(-1, 1), random(3, 4), 0, 0, 160);
        goto Super::Spawn;

    }
}

class NukeSplash1_Small : NukeSplash1_Base
{
    Default
    {
    Scale 0.4;
    }
}

class NukeSplash2_Base : NukeSplash1_Base
{
    Default
    {
    Translation "112:127 = [105, 143, 1]:[197, 255, 1]";
    }
}

class NukeSplash2_Small : NukeSplash2_Base
{
    Default
    {
    Scale 0.4;
    }
}

////////////////////////////////////////////////////////////////
//
// Water splashes
//
////////////////////////////////////////////////////////////////

class WaterSplash1 : WaterSplash
{
    Default
    {
    +FORCEYBILLBOARD;
    Translation "192:207 = [0, 11, 19]:[15, 42, 95]", "240:247 = [0, 11, 19]:[15, 42, 95]";
    Renderstyle "Translucent";
    Alpha 0.5;
    }
}

class WaterSplash1_Base : WaterSplashBase
{
    Default
    {
    +FORCEYBILLBOARD;
    Translation "192:207 = [0, 11, 19]:[15, 42, 95]", "240:247 = [0, 11, 19]:[15, 42, 95]";
    Renderstyle "Translucent";
    Alpha 0.5;
    }
}

class WaterSplash1_Small : WaterSplash1_Base
{
    Default
    {
    Scale 0.4;
    }
}

class WaterSplash2 : WaterSplash1
{
    Default
    {
    Translation "192:207 = [7, 15, 29]:[139, 115, 91]", "240:247 = [7, 15, 29]:[139, 115, 91]";
    }
}

class WaterSplash2_Base : WaterSplash1_Base
{
    Default
    {
    Translation "192:207 = [7, 15, 29]:[139, 115, 91]", "240:247 = [7, 15, 29]:[139, 115, 91]";
    Alpha 0.25;
    }
}

class WaterSplash2_Small : WaterSplash2_Base
{
    Default
    {
    Scale 0.4;
    }
}

class WaterSplash3 : WaterSplash1
{
    Default
    {
    Translation "192:207 = [15, 22, 7]:[14, 48, 19]", "240:247 = [15, 22, 7]:[14, 48, 19]";
    }
}

class WaterSplash3_Base : WaterSplash1_Base
{
    Default
    {
    Translation "192:207 = [15, 22, 7]:[14, 48, 19]", "240:247 = [15, 22, 7]:[14, 48, 19]";
    }
}

class WaterSplash3_Small : WaterSplash3_Base
{
    Default
    {
    Scale 0.4;
    }
}

class WaterSplash4 : WaterSplash1
{
    Default
    {
    Translation "192:207 = [7, 7, 7]:[67, 67, 67]", "240:247 = [7, 7, 7]:[67, 67, 67]";
    }
}

class WaterSplash4_Base : WaterSplash1_Base
{
    Default
    {
    Translation "192:207 = [7, 7, 7]:[67, 67, 67]", "240:247 = [7, 7, 7]:[67, 67, 67]";
    }
}

class WaterSplash4_Small : WaterSplash4_Base
{
    Default
    {
    Scale 0.4;
    }
}

class BloodSplash2 : WaterSplash1
{
    Default
    {
    Translation "192:207 = [67, 0, 0]:[139, 0, 0]", "240:247 = [67, 0, 0]:[139, 0, 0]";
    }
}

class BloodSplash2_Base : WaterSplash1_Base
{
    Default
    {
    Translation "192:207 = [67, 0, 0]:[139, 0, 0]", "240:247 = [67, 0, 0]:[139, 0, 0]";
    }
}

class BloodSplash2_Small : BloodSplash2_Base
{
    Default
    {
    Scale 0.4;
    }
}
