//=====Anything torchy... or burning barrely=====//
//By Keksdose, adjustments made by Ghastly_Dragon

/*Actor FXRedTorch : RedTorch Replaces RedTorch
{
    States
    {
    Spawn:
        TNT1 A 0
        TNT1 A 0 A_SpawnItemEx("RedTorchFlare",0,0,55)
        TNT1 A 0 A_CheckSight(4)
        TNT1 A 0 A_Jump(128,2)
        TBLX A 1 A_SpawnItemEx("RedTorchFire1",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400))
        Goto Spawn
        TBLX A 1 A_SpawnItemEx("RedTorchFire2",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400))
        Goto Spawn
        TBLX A 1
        Goto Spawn
    }
}

class FXShortRedTorch : ShortRedTorch replaces ShortRedTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("RedTorchFlare",0,0,30);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        SMRX A 1 A_SpawnItemEx("RedTorchFire1",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1 A_SpawnItemEx("RedTorchFire2",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1;
        Goto Spawn;

    }
}*/

class RedTorchFlare : Actor
{
    Default
    {
    +CLIENTSIDE;
    +NoGravity;
    +NoInteraction;
    +NoBlockmap;
    +ForceXYBillboard;
    +NoTeleport;
    RenderStyle "Add";
    Scale 0.4;
    Alpha 0.6;
    }
    States
    {
    Spawn:
        RFLR A 2 Bright;
        Stop;

    }
}

class RedTorchFire1 : RedTorchFlare
{
    Default
    {
    Alpha 1;
    Radius 0;
    Height 0;
    Scale 0.175;
    }
    States
    {
    Spawn:
        FIR1 ABCDEFG 1 Bright;
        FIR1 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class RedTorchFire2 : RedTorchFire1
{
    States
    {
    Spawn:
        FIR2 ABCDEFG 1 Bright;
        FIR2 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

/*Actor FXBlueTorch : BlueTorch Replaces BlueTorch
{
    States
    {
    Spawn:
        TNT1 A 0
        TNT1 A 0 A_SpawnItemEx("BlueTorchFlare",0,0,55)
        TNT1 A 0 A_CheckSight(4)
        TNT1 A 0 A_Jump(128,2)
        TBLX A 1 A_SpawnItemEx("BlueTorchFire1",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400))
        Goto Spawn
        TBLX A 1 A_SpawnItemEx("BlueTorchFire2",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400))
        Goto Spawn
        TBLX A 1
        Goto Spawn
    }
}

class FXShortBlueTorch : ShortBlueTorch replaces ShortBlueTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("BlueTorchFlare",0,0,30);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        SMRX A 1 A_SpawnItemEx("BlueTorchFire1",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1 A_SpawnItemEx("BlueTorchFire2",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1;
        Goto Spawn;

    }
}*/

class BlueTorchFire1 : RedTorchFire1
{
    States
    {
    Spawn:
        FIB1 ABCDEFG 1 Bright;
        FIB1 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class BlueTorchFire2 : BlueTorchFire1
{
    States
    {
    Spawn:
        FIB2 ABCDEFG 1 Bright;
        FIB2 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class BlueTorchFlare : RedTorchFlare
{
    States
    {
    Spawn:
        BFLR A 2 Bright;
        Stop;

    }
}

/*Actor FXGreenTorch : GreenTorch Replaces GreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0
        TNT1 A 0 A_SpawnItemEx("GreenTorchFlare",0,0,55)
        TNT1 A 0 A_CheckSight(4)
        TNT1 A 0 A_Jump(128,2)
        TBLX A 1 A_SpawnItemEx("GreenTorchFire1",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400))
        Goto Spawn
        TBLX A 1 A_SpawnItemEx("GreenTorchFire2",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400))
        Goto Spawn
        TBLX A 1
        Goto Spawn
    }
}

class FXShortGreenTorch : ShortGreenTorch replaces ShortGreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("GreenTorchFlare",0,0,30);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        SMRX A 1 A_SpawnItemEx("GreenTorchFire1",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1 A_SpawnItemEx("GreenTorchFire2",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1;
        Goto Spawn;

    }
}*/

class GreenTorchFire1 : RedTorchFire1
{
    States
    {
    Spawn:
        FIG1 ABCDEFG 1 Bright;
        FIG1 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class GreenTorchFire2 : GreenTorchFire1
{
    States
    {
    Spawn:
        FIG2 ABCDEFG 1 Bright;
        FIG2 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class GreenTorchFlare : RedTorchFlare
{
    States
    {
    Spawn:
        GFLR A 2 Bright;
        Stop;

    }
}

class FXBurningBarrel : BurningBarrel replaces BurningBarrel
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("BarrelFlare",0,0,30);
        TNT1 A 0 A_CheckSight(6);
        TNT1 A 0 A_Jump(128,2);
        FCAN AAA 0 A_SpawnItemEx("BarrelFire",Random(-6,6),Random(-6,6),Random(24,28),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        FCAN A 1;
        Goto Spawn;
        FCAN A 1;
        Goto Spawn;

    }
}

class BarrelFlare : RedTorchFlare
{
    Default
    {
 Scale 0.45;
 RenderStyle "Add";
 Alpha 1;
    }
    States
    {
    Spawn:
        RFLR A 2;
        Stop;

    }
}

class BarrelFire : RedTorchFire1
{
    Default
    {
 Scale 0.185;
    }
}

// ************* Additional Colors by Tormentor667 ************* //

////////////////
//Yellow Torch//
////////////////

class FXYellowTorch : GreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("YellowTorchFlare",0,0,55);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        TBLX A 1 A_SpawnItemEx("YellowTorchFire1",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        TBLX A 1 A_SpawnItemEx("YellowTorchFire2",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        TBLX A 1;
        Goto Spawn;

    }
}

class FXShortYellowTorch : ShortGreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("YellowTorchFlare",0,0,30);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        SMRX A 1 A_SpawnItemEx("YellowTorchFire1",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1 A_SpawnItemEx("YellowTorchFire2",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1;
        Goto Spawn;

    }
}

class YellowTorchFire1 : RedTorchFire1
{
    States
    {
    Spawn:
        FIY1 ABCDEFG 1 Bright;
        FIY1 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class YellowTorchFire2 : GreenTorchFire1
{
    States
    {
    Spawn:
        FIY2 ABCDEFG 1 Bright;
        FIY2 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class YellowTorchFlare : RedTorchFlare
{
    States
    {
    Spawn:
        YFLR A 2 Bright;
        Stop;

    }
}

///////////////
//Blood Torch//
///////////////

class FXBloodTorch : GreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("BloodTorchFlare",0,0,55);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        TBLX A 1 A_SpawnItemEx("BloodTorchFire1",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        TBLX A 1 A_SpawnItemEx("BloodTorchFire2",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        TBLX A 1;
        Goto Spawn;

    }
}

class FXShortBloodTorch : ShortGreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("BloodTorchFlare",0,0,30);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        SMRX A 1 A_SpawnItemEx("BloodTorchFire1",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1 A_SpawnItemEx("BloodTorchFire2",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1;
        Goto Spawn;

    }
}

class BloodTorchFire1 : RedTorchFire1
{
    States
    {
    Spawn:
        FIX1 ABCDEFG 1 Bright;
        FIX1 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class BloodTorchFire2 : GreenTorchFire1
{
    States
    {
    Spawn:
        FIX2 ABCDEFG 1 Bright;
        FIX2 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class BloodTorchFlare : RedTorchFlare
{
    States
    {
    Spawn:
        XFLR A 2 Bright;
        Stop;

    }
}

////////////////
//Purple Torch//
////////////////

class FXPurpleTorch : GreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("PurpleTorchFlare",0,0,55);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        TBLX A 1 A_SpawnItemEx("PurpleTorchFire1",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        TBLX A 1 A_SpawnItemEx("PurpleTorchFire2",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        TBLX A 1;
        Goto Spawn;

    }
}

class FXShortPurpleTorch : ShortGreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("PurpleTorchFlare",0,0,30);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        SMRX A 1 A_SpawnItemEx("PurpleTorchFire1",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1 A_SpawnItemEx("PurpleTorchFire2",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1;
        Goto Spawn;

    }
}

class PurpleTorchFire1 : RedTorchFire1
{
    States
    {
    Spawn:
        FIP1 ABCDEFG 1 Bright;
        FIP1 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class PurpleTorchFire2 : GreenTorchFire1
{
    States
    {
    Spawn:
        FIP2 ABCDEFG 1 Bright;
        FIP2 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class PurpleTorchFlare : RedTorchFlare
{
    States
    {
    Spawn:
        PFLR A 2 Bright;
        Stop;

    }
}

///////////////
//White Torch//
///////////////

class FXWhiteTorch : GreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("WhiteTorchFlare",0,0,55);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        TBLX A 1 A_SpawnItemEx("WhiteTorchFire1",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        TBLX A 1 A_SpawnItemEx("WhiteTorchFire2",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        TBLX A 1;
        Goto Spawn;

    }
}

class FXShortWhiteTorch : ShortGreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("WhiteTorchFlare",0,0,30);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        SMRX A 1 A_SpawnItemEx("WhiteTorchFire1",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1 A_SpawnItemEx("WhiteTorchFire2",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1;
        Goto Spawn;

    }
}

class WhiteTorchFire1 : RedTorchFire1
{
    States
    {
    Spawn:
        FIW1 ABCDEFG 1 Bright;
        FIW1 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class WhiteTorchFire2 : GreenTorchFire1
{
    States
    {
    Spawn:
        FIW2 ABCDEFG 1 Bright;
        FIW2 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class WhiteTorchFlare : RedTorchFlare
{
    States
    {
    Spawn:
        WFLR A 2 Bright;
        Stop;

    }
}

//////////////
//Cyan Torch//
//////////////

class FXCyanTorch : GreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("CyanTorchFlare",0,0,55);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        TBLX A 1 A_SpawnItemEx("CyanTorchFire1",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        TBLX A 1 A_SpawnItemEx("CyanTorchFire2",Random(-2,2),Random(-2,2),Random(53,55),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        TBLX A 1;
        Goto Spawn;

    }
}

class FXShortCyanTorch : ShortGreenTorch
{
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("CyanTorchFlare",0,0,30);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        SMRX A 1 A_SpawnItemEx("CyanTorchFire1",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1 A_SpawnItemEx("CyanTorchFire2",Random(-2,2),Random(-2,2),Random(28,30),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(1000,2400));
        Goto Spawn;
        SMRX A 1;
        Goto Spawn;

    }
}

class CyanTorchFire1 : RedTorchFire1
{
    States
    {
    Spawn:
        FIC1 ABCDEFG 1 Bright;
        FIC1 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class CyanTorchFire2 : GreenTorchFire1
{
    States
    {
    Spawn:
        FIC2 ABCDEFG 1 Bright;
        FIC2 HIJKL 1 Bright A_FadeOut(0.15);
        Stop;

    }
}

class CyanTorchFlare : RedTorchFlare
{
    States
    {
    Spawn:
        CFLR A 2 Bright;
        Stop;

    }
}

//////////////////
// WALL TORCHES //
//////////////////

class FXRedWallTorch : RedTorch
{
    Default
    {
 +NOGRAVITY;
    }
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("RedTorchFlare",0,0,35);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        WLTR A 1 A_SpawnItemEx("RedTorchFire1",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1 A_SpawnItemEx("RedTorchFire2",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1;
        Goto Spawn;

    }
}

class FXYellowWallTorch : RedTorch
{
    Default
    {
 +NOGRAVITY;
    }
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("YellowTorchFlare",0,0,35);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        WLTR A 1 A_SpawnItemEx("YellowTorchFire1",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1 A_SpawnItemEx("YellowTorchFire2",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1;
        Goto Spawn;

    }
}

class FXGreenWallTorch : RedTorch
{
    Default
    {
 +NOGRAVITY;
    }
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("GreenTorchFlare",0,0,35);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        WLTR A 1 A_SpawnItemEx("GreenTorchFire1",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1 A_SpawnItemEx("GreenTorchFire2",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1;
        Goto Spawn;

    }
}

class FXPurpleWallTorch : RedTorch
{
    Default
    {
 +NOGRAVITY;
    }
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("PurpleTorchFlare",0,0,35);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        WLTR A 1 A_SpawnItemEx("PurpleTorchFire1",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1 A_SpawnItemEx("PurpleTorchFire2",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1;
        Goto Spawn;

    }
}

class FXBloodRedWallTorch : RedTorch
{
    Default
    {
 +NOGRAVITY;
    }
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("BloodTorchFlare",0,0,35);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        WLTR A 1 A_SpawnItemEx("BloodTorchFire1",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1 A_SpawnItemEx("BloodTorchFire2",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1;
        Goto Spawn;

    }
}

class FXCyanWallTorch : RedTorch
{
    Default
    {
 +NOGRAVITY;
    }
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("CyanTorchFlare",0,0,35);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        WLTR A 1 A_SpawnItemEx("CyanTorchFire1",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1 A_SpawnItemEx("CyanTorchFire2",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1;
        Goto Spawn;

    }
}

class FXWhiteWallTorch : RedTorch
{
    Default
    {
 +NOGRAVITY;
    }
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("WhiteTorchFlare",0,0,35);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        WLTR A 1 A_SpawnItemEx("WhiteTorchFire1",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1 A_SpawnItemEx("WhiteTorchFire2",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1;
        Goto Spawn;

    }
}

class FXBlueWallTorch : RedTorch
{
    Default
    {
 +NOGRAVITY;
    }
    States
    {
    Spawn:
        TNT1 A 0;
        TNT1 A 0 A_SpawnItemEx("BlueTorchFlare",0,0,35);
        TNT1 A 0 A_CheckSight(4);
        TNT1 A 0 A_Jump(128,2);
        WLTR A 1 A_SpawnItemEx("BlueTorchFire1",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1 A_SpawnItemEx("BlueTorchFire2",Random(-2,2),Random(-2,2),Random(30,32),0.001 * Random(10,200),0.001 * Random(10,200),0.001 * Random(100,2000));
        Goto Spawn;
        WLTR A 1;
        Goto Spawn;

    }
}
