class TCOTDMoon : TCOTDSimpleActor
{
	Default
	{
		//$Category Special Actors (TCOTD2)
		//$Title Moon
		Radius 16;
		Height 16;
		Alpha 1.0;
		YScale 0.8333;
		Mass 5;
		+NOINTERACTION
		+FORCEXYBILLBOARD
		//+INVISIBLEINMIRRORS
	}

	States
	{
	Spawn:
		MOON Z -1 Bright;
		Stop;
	}
}

/*
class TCOTDMoon2 : TCOTDMoon
{
	Default
	{
		//$Title Moon (reflection only)
		+ONLYVISIBLEINMIRRORS
		-INVISIBLEINMIRRORS
		-FORCEXYBILLBOARD
	}
}
*/
