



//The following actors change hanging bodies to be shootable and bleeding. However, it's meant
//to work with the aformentioned omitted bloodsprite actor, and it also takes away the ability
//to shoot through the bodies themselves (could break maps). They're here though, in case
//anyone's interested.

//***** DECORATIONS *****

// Bloody twitch -----------------------------------------------------------
class NashGore_BloodyTwitch : BloodyTwitch replaces BloodyTwitch
{
    Default
    {

        Mass 0x7FFFFFFF; // [Blue Shadow] "infinite" mass
        Health -1;
        +SHOOTABLE
    }
}

// Meat 2 ------------------------------------------------------------------
class NashGore_Meat2 : Meat2 replaces Meat2
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
    }
}

// Meat 3 ------------------------------------------------------------------
class NashGore_Meat3 : Meat3 replaces Meat3
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
    }
}

// Meat 4 ------------------------------------------------------------------
class NashGore_Meat4 : Meat4 replaces Meat4
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
    }
}

// Meat 5 ------------------------------------------------------------------
class NashGore_Meat5 : Meat5 replaces Meat5
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
    }
}

// Nonsolid meat -----------------------------------------------------------
class NashGore_NonsolidMeat2 : NashGore_Meat2 replaces NonsolidMeat2
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}
class NashGore_NonsolidMeat3 : NashGore_Meat3 replaces NonsolidMeat3
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}
class NashGore_NonsolidMeat4 : NashGore_Meat4 replaces NonsolidMeat4
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}
class NashGore_NonsolidMeat5 : NashGore_Meat5 replaces NonsolidMeat5
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}

// Nonsolid bloody twitch --------------------------------------------------
class NashGore_NonsolidTwitch : NashGore_BloodyTwitch replaces NonsolidTwitch
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}

// Dead on a stick ---------------------------------------------------------
class NashGore_DeadStick : DeadStick replaces DeadStick
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}

// Still alive on a stick --------------------------------------------------
class NashGore_LiveStick : LiveStick replaces LiveStick
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}

// Hanging with no guts ----------------------------------------------------
class NashGore_HangNoGuts : HangNoGuts replaces HangNoGuts
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}

// Hanging from bottom with no brain ---------------------------------------
class NashGore_HangBNoBrain : HangBNoBrain replaces HangBNoBrain
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}

// Hanging from top, looking down ------------------------------------------
class NashGore_HangTLookingDown : HangTLookingDown replaces HangTLookingDown
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}

// Hanging from top, looking up --------------------------------------------
class NashGore_HangTLookingUp : HangTLookingUp replaces HangTLookingUp
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}

// Hanging from top, skully ------------------------------------------------
class NashGore_HangTSkull : HangTSkull replaces HangTSkull
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}

// Hanging from top without a brain ----------------------------------------
class NashGore_HangTNoBrain : HangTNoBrain replaces HangTNoBrain
{
    Default
    {

        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
    }
}

// And now, the new props


// Tortured Cyber (from cybergore.txt) I'm not sure if the other parts should bleed
// If you will use this, remove the actor from the other text file
class TorturedCyber : Actor
{
    Default
    {

        Height 91;
        Radius 25;
        Mass 0x7FFFFFFF;
        Health -1;
        +SHOOTABLE
        +NOTAUTOAIMED
        +SOLID
        +SPAWNCEILING
        +NOGRAVITY

    }
    States
    {

        Spawn:
            CYBT A -1;
            Stop;

    }
}

// Elastic Flesh (from elasticflesh.txt)
// If you will use this, remove the other text file
class ElasticFlesh : Actor
{
    Default
    {

        Radius 16;
        Height 16;
        Mass 0x7FFFFFFF;
        Health -1;
        +NOGRAVITY
        +RANDOMIZE
        +SHOOTABLE
        +NOTAUTOAIMED

    }
    States
    {

        Spawn:
            TNT1 A 0;
            TNT1 A 0 A_Jump (256, "Delay1", "Delay2", "Delay3");
        Delay1:
            MELF A 4;
            goto Squidgy;
        Delay2:
            MELF A 8;
            goto Squidgy;
        Delay3:
            MELF A 12;
            goto Squidgy;
        Squidgy:
            MELF A 4 A_SetScale (1, 0.97);
            MELF A 4 A_SetScale (1, 0.93);
            MELF A 4 A_SetScale (1, 0.91);
            MELF A 4 A_SetScale (1, 0.9);
            MELF A 4 A_SetScale (1, 0.91);
            MELF A 4 A_SetScale (1, 0.93);
            Loop;

    }
}
class ElasticFlesh2 : Actor
{
    Default
    {

        Radius 16;
        Height 16;
        +NOGRAVITY
        +RANDOMIZE
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            TNT1 A 0;
            TNT1 A 0 A_Jump (256, "Delay1", "Delay2", "Delay3");
        Delay1:
            MELF B 4;
            goto Squidgy;
        Delay2:
            MELF B 8;
            goto Squidgy;
        Delay3:
            MELF B 12;
            goto Squidgy;
        Squidgy:
            MELF B 4 A_SetScale (1, 0.97);
            MELF B 4 A_SetScale (1, 0.93);
            MELF B 4 A_SetScale (1, 0.91);
            MELF B 4 A_SetScale (1, 0.9);
            MELF B 4 A_SetScale (1, 0.91);
            MELF B 4 A_SetScale (1, 0.93);
            Loop;

    }
}

// Some Gore (from gorehell.txt, the useless text file that I made for stuff like this)
// If you will use this, remove these actors from the other text file
class CarcassImpaledMarine : Actor
{
    Default
    {

        //$Category Decoration
        +Solid
        +SHOOTABLE
        +NOTAUTOAIMED
        Height 48;
        Radius 20;
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            MPLD A -1;
            Stop;

    }
}
class CarcassImpaledMarine2 : Actor
{
    Default
    {

        //$Category Decoration
        +Solid
        +SHOOTABLE
        +NOTAUTOAIMED
        Height 48;
        Radius 20;
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            MPL2 A -1;
            Stop;

    }
}

// More Gore (from gorepack.txt)
// If you will use this, remove the other text file
class Meat6 : Actor
{
    Default
    {

        //$Category Decoration

        Radius 16;
        Height 52;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            GOR6 A -1;
            Stop;

    }
}
class Meat7 : Actor
{
    Default
    {

        //$Category Decoration

        Radius 16;
        Height 52;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            GOR7 A -1;
            Stop;

    }
}
class Meat8 : Actor
{
    Default
    {

        //$Category Decoration

        Radius 16;
        Height 52;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            GOR8 A -1;
            Stop;

    }
}
class Meat9 : Actor
{
    Default
    {

        //$Category Decoration

        Radius 16;
        Height 52;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            GOR9 A -1;
            Stop;

    }
}
class Meat10 : Actor
{
    Default
    {

        //$Category Decoration

        Radius 16;
        Height 52;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            GORA A -1;
            Stop;

    }
}

// Hanged Marines (from hangedmarines.txt) only the blocking ones (because why they shouldn't?)
// If you will use this, remove the other text file
class HangedMarine1Blocking : Actor
{
    Default
    {


        Radius 22;
        Height 54;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            HMAR A -1;
            Stop;

    }
}
class HangedMarine2Blocking : Actor
{
    Default
    {


        Radius 22;
        Height 55;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            HMAR B -1;
            Stop;

    }
}
class HangedMarine3Blocking : Actor
{
    Default
    {


        Radius 22;
        Height 54;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            HMAR C -1;
            Stop;

    }
}

// More Hanged Marines (from hangingmarines.txt)
// If you will use this, remove the other text file
class CTHangPlayer1 : Actor
{
    Default
    {

        Radius 16;
        Height 88;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            HANP A -1;
            Stop;

    }
}
class CTHangPlayer2 : Actor
{
    Default
    {

        Radius 16;
        Height 88;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            HANP B -1;
            Stop;

    }
}

// Hanging Thingies (from marinemeat.txt)
// If you will use this, remove the other text file
class CTHangMarineLimb : Actor
{
    Default
    {

        Radius 16;
        Height 68;
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            HANL A -1;
            Stop;

    }
}
class CTHangMarineTorso : Actor
{
    Default
    {

        Radius 16;
        Height 52;
        +NOGRAVITY
        +SPAWNCEILING
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            HANL B -1;
            Stop;

    }
}

// Skewered Corpses (from skeweredcorpses.txt)
// If you will use this, remove the other text file
class ChestSkewered1 : Actor
{
    Default
    {

        Radius 16;
        Height 64;
        +SOLID
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            POLC A -1;
            Stop;

    }
}
class ChestSkewered2 : Actor
{
    Default
    {

        Radius 16;
        Height 64;
        +SOLID
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            POLC B -1;
            Stop;

    }
}
class ChestSkewered3 : Actor
{
    Default
    {

        Radius 16;
        Height 64;
        +SOLID
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;

    }
    States
    {

        Spawn:
            POLC C -1;
            Stop;

    }
}

// Dat Tortured Goat (from torturedbaron.txt)
// And you know the rest...
class TorturedBaron : Actor
{
    Default
    {

        Height 80;
        Radius 20;
        +Solid
        +SpawnCeiling
        +NoGravity
        +SHOOTABLE
        +NOTAUTOAIMED
        Mass 0x7FFFFFFF;
        Health -1;
        BloodColor "6C A0 40"; //"7D 9D 59" This should have any use, I guess

    }
    States
    {

        Spawn:
            NJDH A -1;
            Stop;

    }
}

//Fin
