class Head1 : Actor
{
    Default
    {

        //$Category Decoration
        Radius 20;
        Height 4;

    }
    States
    {

        Spawn:
            HED1 A -1;
            Loop;

    }
}
class Head2 : Actor
{
    Default
    {

        //$Category Decoration
        Radius 20;
        Height 4;

    }
    States
    {

        Spawn:
            HED2 A -1;
            Loop;

    }
}
class Head3 : Actor
{
    Default
    {

        //$Category Decoration
        Radius 20;
        Height 4;

    }
    States
    {

        Spawn:
            HED3 A -1;
            Loop;

    }
}
class Head4 : Actor
{
    Default
    {

        //$Category Decoration
        Radius 20;
        Height 4;

    }
    States
    {

        Spawn:
            HED4 A -1;
            Loop;

    }
}
