class BurningCorpse1 : Actor
{
    Default
    {

        +SOLID
        Radius 8;
        Height 108;

    }
    States
    {

        Spawn:
            BAVE ABCD 4 Bright;
            Loop;
        Inactive:
            ALVE A 1;
            Loop;
    }
}
class BurningCorpse2 : Actor
{
    Default
    {

        +SOLID
        Radius 8;
        Height 108;

    }
    States
    {

        Spawn:
            BAV2 ABCD 4 Bright;
            Loop;
        Inactive:
            ALV2 A 1 A_StopSoundEx("SoundSlot7");
            Loop;
    }
}
