class TorturedCyber : Actor
{
    Default
    {

        Height 91;
        Radius 25;
        +SOLID
        +SPAWNCEILING
        +NOGRAVITY

    }
    States
    {

        Spawn:
            CYBT A -1;
            Stop;

    }
}
class Cyberarm : Actor
{
    Default
    {

    }
    States
    {

        Spawn:
            CARM A -1;
            Stop;

    }
}
class Rocketarm : Actor
{
    Default
    {

        Height 80;
        Radius 5;
        +SPAWNCEILING
        +NOGRAVITY
        +SOLID

    }
    States
    {

        Spawn:
            HARM A -1;
            Stop;

    }
}
class Fleshleg : Actor
{
    Default
    {

    }
    States
    {

        Spawn:
            FLEG A -1;
            Stop;

    }
}
class Cyberleg : Actor
{
    Default
    {

        Height 17;
        radius 13;
        +SOLID

    }
    States
    {

        Spawn:
            RLEG D -1;
            Stop;

    }
}
