class DarkLamp1 : Actor
{
    Default
    {

        //$Category Light sources
        Radius 16;
        Height 75;
        +SOLID

    }
    States
    {

        Spawn:
            D641 A -1 Bright;
            Stop;
    }
}
class DarkLamp2 : Actor
{
    Default
    {

        //$Category Light sources
        Radius 16;
        Height 60;
        +SOLID

    }
    States
    {

        Spawn:
            D642 A -1 Bright;
            Stop;
    }
}
class DarkLampCeiling1 : Actor
{
    Default
    {

        //$Category Light sources
        Radius 10;
        Height 55;
        +SOLID
        +SPAWNCEILING
        +NOGRAVITY

    }
    States
    {

        Spawn:
            D643 A -1 Bright;
            Stop;
    }
}
class DarkLampCeiling2 : Actor
{
    Default
    {

        //$Category Light sources
        Radius 8;
        Height 8;
        -SOLID
        +SPAWNCEILING
        +NOGRAVITY

    }
    States
    {

        Spawn:
            D644 A -1 Bright;
            Stop;
    }
}
