class CarcassImpaledMarine : Actor
{
    Default
    {

        //$Category Decoration
        +Solid
        Height 48;
        Radius 20;

    }
    States
    {

        Spawn:
            MPLD A -1;
            Stop;

    }
}
class CarcassImpaledMarine2 : Actor
{
    Default
    {

        //$Category Decoration
        +Solid
        Height 48;
        Radius 20;

    }
    States
    {

        Spawn:
            MPL2 A -1;
            Stop;

    }
}
class HellPillar : Actor
{
    Default
    {

        //$Category Decoration
        +Solid
        Height 128;
        Radius 16;

    }
    States
    {

        Spawn:
            HPLR A -1;
            Stop;

    }
}
