class Meat6 : Actor
{
    Default
    {

        //$Category Decoration

        Radius 16;
        Height 52;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            GOR6 A -1;
            Stop;

    }
}
class Meat7 : Actor
{
    Default
    {

        //$Category Decoration

        Radius 16;
        Height 52;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            GOR7 A -1;
            Stop;

    }
}
class Meat8 : Actor
{
    Default
    {

        //$Category Decoration

        Radius 16;
        Height 52;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            GOR8 A -1;
            Stop;

    }
}
class Meat9 : Actor
{
    Default
    {

        //$Category Decoration

        Radius 16;
        Height 52;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            GOR9 A -1;
            Stop;

    }
}
class Meat10 : Actor
{
    Default
    {

        //$Category Decoration

        Radius 16;
        Height 52;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            GORA A -1;
            Stop;

    }
}
