class CTHangPlayer1 : Actor
{
    Default
    {

        Radius 16;
        Height 88;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            HANP A -1;
            Stop;

    }
}
class CTHangPlayer2 : Actor
{
    Default
    {

        Radius 16;
        Height 88;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            HANP B -1;
            Stop;

    }
}
