class HangedMarine1Blocking : Actor
{
    Default
    {


        Radius 22;
        Height 54;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            HMAR A -1;
            Stop;

    }
}
class HangedMarine1 : Actor
{
    Default
    {


        Radius 22;
        Height 54;
        -SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            HMAR A -1;
            Stop;

    }
}
class HangedMarine2Blocking : Actor
{
    Default
    {


        Radius 22;
        Height 55;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            HMAR B -1;
            Stop;

    }
}
class HangedMarine2 : Actor
{
    Default
    {


        Radius 22;
        Height 55;
        -SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            HMAR B -1;
            Stop;

    }
}
class HangedMarine3Blocking : Actor
{
    Default
    {


        Radius 22;
        Height 54;
        +SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            HMAR C -1;
            Stop;

    }
}
class HangedMarine3 : Actor
{
    Default
    {


        Radius 22;
        Height 54;
        -SOLID
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            HMAR C -1;
            Stop;

    }
}
