// [XA] Moved common traits to base items. Original by DavidRaven
class FlaskBase : Actor
{
    Default
    {

        mass 1500;
        Health 1;
        Radius 6;
        Height 17;
        //+SOLID
        +SHOOTABLE
        +NOBLOOD
        +ACTIVATEMCROSS
        +DONTGIB
        +NOICEDEATH
        RenderStyle "STYLE_Translucent";
        DeathSound "tubes/break";

    }
    States
    {

        Spawn:
            TNT1 A -1;
            loop;
        Death:
            TNT1 A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_Scream;
            Stop;

    }
}
class flaskblueA : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS A -1;
            loop;

    }
}
class flaskblueB : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS G -1;
            loop;

    }
}
class flaskpurpleA : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS B -1;
            loop;

    }
}
class flaskpurpleB : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS H -1;
            loop;

    }
}
class flaskredA : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS C -1;
            loop;

    }
}
class flaskredB : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS I -1;
            loop;

    }
}
class flaskgreenA : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS D -1;
            loop;

    }
}
class flaskgreenB : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS J -1;
            loop;

    }
}
class flaskyellowA : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS E -1;
            loop;

    }
}
class flaskyellowB : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS K -1;
            loop;

    }
}
class flaskgreyA : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS F -1;
            loop;

    }
}
class flaskgreyB : FlaskBase
{
    Default
    {

    }
    States
    {

        Spawn:
            FLKS L -1;
            loop;

    }
}
class GlassBase : FlaskBase
{
    Default
    {

        Radius 3;
        Height 8;

    }
    States
    {

        Death:
            TNT1 A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard1", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_SpawnItemEx ("Flaskshard2", 0, 0, random (3, 5), random (-5, 5), random (-5, 5), random (1, 2), 0, 0, 30);
            TNT1 A 0 A_Scream;
            Stop;

    }
}
class glassblue : GlassBase
{
    Default
    {

    }
    States
    {

        Spawn:
            BEAK A -1;
            loop;

    }
}
class glasspurple : GlassBase
{
    Default
    {

    }
    States
    {

        Spawn:
            BEAK B -1;
            loop;

    }
}
class glassred : GlassBase
{
    Default
    {

    }
    States
    {

        Spawn:
            BEAK C -1;
            loop;

    }
}
class glassgreen : GlassBase
{
    Default
    {

    }
    States
    {

        Spawn:
            BEAK D -1;
            loop;

    }
}
class glassyellow : GlassBase
{
    Default
    {

    }
    States
    {

        Spawn:
            BEAK E -1;
            loop;

    }
}
class glassgrey : GlassBase
{
    Default
    {

    }
    States
    {

        Spawn:
            BEAK F -1;
            loop;

    }
}
class ShardBase : Actor
{
    Default
    {

        Radius 2;
        Height 4;
        speed 2;
        mass 1;
        RenderStyle "STYLE_Translucent";
        Alpha 0.6;
        +NOBLOCKMAP
        +MISSILE
        +NOTELEPORT
        +DONTSPLASH
        +NOICEDEATH
    }
}
class flaskshard1 : ShardBase
{
    Default
    {

    }
    States
    {

        Spawn:
            TSR1 ABC 4;
            TSR1 D 4;
            TSR1 ABC 4;
            TSR1 D 4 A_Jump (24, "DeathA");
            TSR1 ABC 4;
            TSR1 D 4;
            TSR1 ABC 4;
            TSR1 D 4 A_Jump (24, "DeatB");
            Loop;
        DeathA:
            TSR1 C 5 A_Jump (80, "DeathA2");
            TNT1 A 1;
            Stop;
        DeathB:
            TSR1 D 5 A_Jump (80, "DeathB2");
            TNT1 A 1;
            Stop;
        DeathA2:
            TSR1 C 3 A_Jump (24, "DeathA2");
            TNT1 A 1;
            Stop;
        DeathB2:
            TSR1 D 5 A_Jump (24, "DeathB2");
            TNT1 A 1;
            Stop;

    }
}
class flaskshard2 : ShardBase
{
    Default
    {

    }
    States
    {

        Spawn:
            TSR2 ADB 4;
            TSR2 C 4;
            TSR2 ADB 4;
            TSR2 C 4 A_Jump (24, "DeathA");
            TSR2 ADB 4;
            TSR2 C 4;
            TSR2 ADB 4;
            TSR2 C 4 A_Jump (24, "DeathB");
            Loop;
        DeathA:
            TSR2 C 5 A_Jump (80, "DeathA2");
            TNT1 A 1;
            Stop;
        DeathB:
            TSR2 D 5 A_Jump (80, "DeathB2");
            TNT1 A 1;
            Stop;
        DeathA2:
            TSR2 C 3 A_Jump (24, "DeathA2");
            TNT1 A 1;
            Stop;
        DeathB2:
            TSR2 D 5 A_Jump (24, "DeathB2");
            TNT1 A 1;
            Stop;

    }
}
