// Colored sets of various columns/pillars.
// Duplicates with the standard Doom columns are not provided.
//
// The following colors are all in the Doom palette:
// Green and red are the original colors. Red is very bright.
// Blue is the cartoonish blue color mostly seen in some Wolf walls.
// Grey is desaturated.
// Bicolor is green and a lighter grey.
// Black is dark grey.
//
// The following colors aren't in the Doom palette:
// Dark red adapts well to palettization. It is less cartoony than bright red.
// Orange adapts well enough to palettization, but quality loss is visible.
//
// Since ZDCMP2 is for ZDoom, mauve has been cut.
class TallColumnBase : Actor
{
    Default
    {

        Radius 16;
        Height 128;
        +SOLID
    }
}
class SpiralColumnBase : Actor
{
    Default
    {

        Radius 16;
        Height 72;
        +SOLID
    }
}
class MediumColumnBase : Actor
{
    Default
    {

        Radius 16;
        Height 52;
        +SOLID
    }
}
class SmallColumnBase : Actor
{
    Default
    {

        Radius 16;
        Height 40;
        +SOLID
    }
}

// Fluted A	  J		Green       7
// Smooth B	  K		Red         8
// Medium C	  L		Blue        9
// Small  D	  M		Grey        1 + 2nd col
// Skull  E   N		Bicolor     2 + 2nd col
// Heart  F/G O/P	Black		3 + 2nd col
// Vine   H   Q		Dark Red	4 + 2nd col
// Spiral I   R		Orange      5 + 2nd col
// Tan    0 + 2nd  	Mauve       6 + 2nd col
class FlutedGreenColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL7 A -1;
            Stop;

    }
}
class FlutedRedColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL8 A -1;
            Stop;

    }
}
class FlutedBlueColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL9 A -1;
            Stop;

    }
}
class FlutedTanColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL0 J -1;
            Stop;

    }
}
class FlutedGreyColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL1 J -1;
            Stop;

    }
}
class FlutedBicolorColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL2 J -1;
            Stop;

    }
}
class FlutedBlackColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL3 J -1;
            Stop;

    }
}
class FlutedDarkRedColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL4 J -1;
            Stop;

    }
}
class FlutedOrangeColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL5 J -1;
            Stop;

    }
}
class SmoothGreenColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL7 B -1;
            Stop;

    }
}
class SmoothRedColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL8 B -1;
            Stop;

    }
}
class SmoothBlueColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL9 B -1;
            Stop;

    }
}
class SmoothTanColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL0 K -1;
            Stop;

    }
}
class SmoothGreyColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL1 K -1;
            Stop;

    }
}
class SmoothBicolorColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL2 K -1;
            Stop;

    }
}
class SmoothBlackColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL3 K -1;
            Stop;

    }
}
class SmoothDarkRedColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL4 K -1;
            Stop;

    }
}
class SmoothOrangeColumn : TallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL5 K -1;
            Stop;

    }
}
class MediumGreenColumn : RandomSpawner
{
    Default
    {
        DropItem "TallGreenColumn";
    }
}
class MediumRedColumn : RandomSpawner
{
    Default
    {
        DropItem "TallRedColumn";
    }
}
class MediumBlueColumn : MediumColumnBase
{
    Default
    {

    }
    States
    {

        Spawn:
            COL9 C -1;
            Stop;

    }
}
class MediumTanColumn : MediumColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL0 L -1;
            Stop;

    }
}
class MediumGreyColumn : MediumColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL1 L -1;
            Stop;

    }
}
class MediumBicolorColumn : MediumColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL2 L -1;
            Stop;

    }
}
class MediumBlackColumn : MediumColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL3 L -1;
            Stop;

    }
}
class MediumDarkRedColumn : MediumColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL4 L -1;
            Stop;

    }
}
class MediumOrangeColumn : MediumColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL5 L -1;
            Stop;

    }
}
class SmallGreenColumn : RandomSpawner
{
    Default
    {
        DropItem "SmallGreenColumn";
    }
}
class SmallRedColumn : RandomSpawner
{
    Default
    {
        DropItem "SmallRedColumn";
    }
}
class SmallBlueColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL9 D -1;
            Stop;

    }
}
class SmallTanColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL0 M -1;
            Stop;

    }
}
class SmallGreyColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL1 M -1;
            Stop;

    }
}
class SmallBicolorColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL2 M -1;
            Stop;

    }
}
class SmallBlackColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL3 M -1;
            Stop;

    }
}
class SmallDarkRedColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL4 M -1;
            Stop;

    }
}
class SmallOrangeColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL5 M -1;
            Stop;

    }
}
class SkullGreenColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL7 E -1;
            Stop;

    }
}
class SkullRedColumn : RandomSpawner
{
    Default
    {
        DropItem "SkullColumn";
    }
}
class SkullBlueColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL9 E -1;
            Stop;

    }
}
class SkullTanColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL0 N -1;
            Stop;

    }
}
class SkullGreyColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL1 N -1;
            Stop;

    }
}
class SkullBicolorColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL2 N -1;
            Stop;

    }
}
class SkullBlackColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL3 N -1;
            Stop;

    }
}
class SkullDarkRedColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL4 N -1;
            Stop;

    }
}
class SkullOrangeColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL5 N -1;
            Stop;

    }
}
class HeartGreenColumn : RandomSpawner
{
    Default
    {
        DropItem "HeartColumn";
    }
}
class HeartRedColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL8 FG 14;
            Loop;

    }
}
class HeartBlueColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL9 FG 14;
            Loop;

    }
}
class HeartTanColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL0 OP 14;
            Loop;

    }
}
class HeartGreyColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL1 OP 14;
            Loop;

    }
}
class HeartBicolorColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL2 OP 14;
            Loop;

    }
}
class HeartBlackColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL3 OP 14;
            Loop;

    }
}
class HeartDarkRedColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL4 OP 14;
            Loop;

    }
}
class HeartOrangeColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL5 OP 14;
            Loop;

    }
}
class VineGreenColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL7 H -1;
            Stop;

    }
}
class VineRedColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL8 H -1;
            Stop;

    }
}
class VineBlueColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL9 H -1;
            Stop;

    }
}
class VineTanColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL0 Q -1;
            Stop;

    }
}
class VineGreyColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL1 Q -1;
            Stop;

    }
}
class VineBicolorColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL2 Q -1;
            Stop;

    }
}
class VineBlackColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL3 Q -1;
            Stop;

    }
}
class VineDarkRedColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL4 Q -1;
            Stop;

    }
}
class VineOrangeColumn : SmallColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL5 Q -1;
            Stop;

    }
}
class SpiralGreenColumn : SpiralColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL7 I -1;
            Stop;

    }
}
class SpiralRedColumn : SpiralColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL8 I -1;
            Stop;

    }
}
class SpiralBlueColumn : SpiralColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL9 I -1;
            Stop;

    }
}
class SpiralTanColumn : SpiralColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL0 R -1;
            Stop;

    }
}
class SpiralGreyColumn : SpiralColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL1 R -1;
            Stop;

    }
}
class SpiralBicolorColumn : SpiralColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL2 R -1;
            Stop;

    }
}
class SpiralBlackColumn : SpiralColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL3 R -1;
            Stop;

    }
}
class SpiralDarkRedColumn : SpiralColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL4 R -1;
            Stop;

    }
}
class SpiralOrangeColumn : SpiralColumnBase
{
    Default
    {

        //$Category Decoration

    }
    States
    {

        Spawn:
            COL5 R -1;
            Stop;

    }
}
