class CTHangMarineLimb : Actor
{
    Default
    {

        Radius 16;
        Height 68;
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            HANL A -1;
            Stop;

    }
}
class CTHangMarineTorso : Actor
{
    Default
    {

        Radius 16;
        Height 52;
        +NOGRAVITY
        +SPAWNCEILING

    }
    States
    {

        Spawn:
            HANL B -1;
            Stop;

    }
}
