//Necrodome trees
class PalmTree1 : Actor
{
    Default
    {

        //$Category Vegetation
        Radius 16;
        Height 128;
        +SOLID

    }
    States
    {

        Spawn:
            PAMN A -1;
            Stop;

    }
}
class PalmTree2 : Actor
{
    Default
    {

        //$Category Vegetation
        Radius 16;
        Height 128;
        +SOLID

    }
    States
    {

        Spawn:
            PAMN B -1;
            Stop;

    }
}
class PalmTree3 : Actor
{
    Default
    {

        //$Category Vegetation
        Radius 16;
        Height 128;
        +SOLID

    }
    States
    {

        Spawn:
            PAMN C -1;
            Stop;

    }
}


//Powerslave tree
class PalmTree4 : Actor
{
    Default
    {

        //$Category Vegetation
        Radius 16;
        Height 160;
        +SOLID

    }
    States
    {

        Spawn:
            PAMP A -1;
            Stop;

    }
}

//Necrodome trees
class BurntPalmTree1 : Actor
{
    Default
    {

        //$Category Vegetation
        Radius 16;
        Height 36;
        +SOLID

    }
    States
    {

        Spawn:
            PAMB A -1;
            Stop;

    }
}
class BurntPalmTree2 : Actor
{
    Default
    {

        //$Category Vegetation
        Radius 16;
        Height 48;
        +SOLID

    }
    States
    {

        Spawn:
            PAMB B -1;
            Stop;

    }
}
class BurntPalmTree3 : Actor
{
    Default
    {

        //$Category Vegetation
        Radius 16;
        Height 64;
        +SOLID

    }
    States
    {

        Spawn:
            PAMB C -1;
            Stop;

    }
}
