class NRock1 : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;

    }
    States
    {

        Spawn:
            NROK A -1;
            Stop;

    }
}
class NRock2 : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;

    }
    States
    {

        Spawn:
            NROK B -1;
            Stop;

    }
}
class NRock3 : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;

    }
    States
    {

        Spawn:
            NROK C -1;
            Stop;

    }
}
class NRock4 : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;

    }
    States
    {

        Spawn:
            NROK D -1;
            Stop;

    }
}
class NRock5 : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;

    }
    States
    {

        Spawn:
            NROK E -1;
            Stop;

    }
}
class NRock6 : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;

    }
    States
    {

        Spawn:
            NROK F -1;
            Stop;

    }
}
class NRock7 : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;

    }
    States
    {

        Spawn:
            NROK G -1;
            Stop;

    }
}
class NRock8 : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;

    }
    States
    {

        Spawn:
            NROK H -1;
            Stop;

    }
}
class NRock9 : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;

    }
    States
    {

        Spawn:
            NROK I -1;
            Stop;

    }
}
class NRock10 : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;

    }
    States
    {

        Spawn:
            NROK J -1;
            Stop;

    }
}
class NRock1small : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;
        Scale 0.6;

    }
    States
    {

        Spawn:
            NROK A -1;
            Stop;

    }
}
class NRock2small : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;
        Scale 0.6;

    }
    States
    {

        Spawn:
            NROK B -1;
            Stop;

    }
}
class NRock3small : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;
        Scale 0.6;

    }
    States
    {

        Spawn:
            NROK C -1;
            Stop;

    }
}
class NRock4small : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;
        Scale 0.6;

    }
    States
    {

        Spawn:
            NROK D -1;
            Stop;

    }
}
class NRock5small : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;
        Scale 0.6;

    }
    States
    {

        Spawn:
            NROK E -1;
            Stop;

    }
}
class NRock6small : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;
        Scale 0.6;

    }
    States
    {

        Spawn:
            NROK F -1;
            Stop;

    }
}
class NRock7small : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;
        Scale 0.6;

    }
    States
    {

        Spawn:
            NROK G -1;
            Stop;

    }
}
class NRock8small : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;
        Scale 0.6;

    }
    States
    {

        Spawn:
            NROK H -1;
            Stop;

    }
}
class NRock9small : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;
        Scale 0.6;

    }
    States
    {

        Spawn:
            NROK I -1;
            Stop;

    }
}
class NRock10small : Actor
{
    Default
    {

        //$Category Rocks
        Radius 16;
        Height 16;
        Scale 0.6;

    }
    States
    {

        Spawn:
            NROK J -1;
            Stop;

    }
}
