class ChestSkewered1 : Actor
{
    Default
    {

        Radius 16;
        Height 64;
        +SOLID

    }
    States
    {

        Spawn:
            POLC A -1;
            Stop;

    }
}
class ChestSkewered2 : Actor
{
    Default
    {

        Radius 16;
        Height 64;
        +SOLID

    }
    States
    {

        Spawn:
            POLC B -1;
            Stop;

    }
}
class ChestSkewered3 : Actor
{
    Default
    {

        Radius 16;
        Height 64;
        +SOLID

    }
    States
    {

        Spawn:
            POLC C -1;
            Stop;

    }
}
