class VTOL : Actor
{
    Default
    {

        //$Category Voxel Vehicles
        //$Title VTOL aircraft
        Radius 64;
        Height 80;
        Mass 200000;
        +SOLID
        +SHOOTABLE
        +NODAMAGE
        +NOBLOOD
        +CANPASS
        Scale 1.5;

    }
    States
    {

        Spawn:
            VTOL A -1;
            Stop;

    }
}
class Forklift : Actor
{
    Default
    {

        //$Category Voxel Vehicles
        //$Title Forklift
        Radius 40;
        Height 96;
        Mass 5000;
        +SOLID
        +SHOOTABLE
        +NODAMAGE
        +NOBLOOD
        +CANPASS
        Scale 1.5;

    }
    States
    {

        Spawn:
            FORK A -1;
            Stop;

    }
}
