class BlueWallTorch : Actor
{
    Default
    {

        +NOBLOCKMAP
        +NOGRAVITY
        +FIXMAPTHINGPOS
        Radius 6.5;

    }
    States
    {

        Spawn:
            BWTR ABCD 4 Bright;
            Loop;

    }
}
class RedWallTorch : Actor
{
    Default
    {

        +NOBLOCKMAP
        +NOGRAVITY
        +FIXMAPTHINGPOS
        Radius 6.5;

    }
    States
    {

        Spawn:
            YWTR ABCD 4 Bright;
            Loop;

    }
}
class GreenWallTorch : Actor
{
    Default
    {

        +NOBLOCKMAP
        +NOGRAVITY
        +FIXMAPTHINGPOS
        Radius 6.5;

    }
    States
    {

        Spawn:
            GWTR ABCD 4 Bright;
            Loop;

    }
}
