// ------------------------------------------------------------------------------------------------
//
// ------------------------------------------------------------------------------------------------

class TCOTDGhostBlood : Actor
{
	Default
	{
		Alpha 0.67;
		RenderStyle "Add";
		Scale 0.9;
		VSpeed 2;
		+DONTSPLASH
		+FORCEXYBILLBOARD
		+NOBLOCKMAP
		+NOGRAVITY
		+NOTELEPORT
		+PUFFGETSOWNER
	}

	States
	{
	Spawn:
		TNT1 AAA 0;
		GBLD ABCDEFG 3;
		Stop;
	}
}
