version "4.3.3"

// Libraries
#include "zscript/INIFile/INIFile.zc"

// Core
#include "zscript/TCOTDGameplayStatics/TCOTDGameplayStatics.zc"
#include "zscript/TCOTDDietActor/TCOTDDietActor.zc"
#include "zscript/TCOTDWeatherFXMixin/TCOTDWeatherFXMixin.zc"
#include "zscript/SpriteShadow/SpriteShadow.zc"

// Sound
#include "zscript/TCOTDSoundPlayer/TCOTDSoundPlayer.zc"
#include "zscript/TCOTDFootstep/TCOTDFootstep.zc"
#include "zscript/TCOTDSiren/TCOTDSiren.zc"

// Items
#include "zscript/TCOTDHealthPickup/TCOTDHealthPickup.zc"
#include "zscript/TCOTDLanternPickup/TCOTDLanternPickup.zc"
#include "zscript/TCOTDLanternOilPickup/TCOTDLanternOilPickup.zc"
#include "zscript/TCOTDPendant/TCOTDPendant.zc"
#include "zscript/TCOTDKey/TCOTDKey.zc"
#include "zscript/TCOTDArmor/TCOTDArmor.zc"

// Bumi (stripped down to snow effects only)
#include "zscript/TCOTDWeatherHandler/TCOTDWeatherHandler.zc"
#include "zscript/TCOTDSnowParticle/TCOTDSnowParticle.zc"

// Weather FX
#include "zscript/TCOTDFogCloud/TCOTDFogCloud.zc"
#include "zscript/TCOTDSnowSpawner/TCOTDSnowSpawner.zc"

// Props and Decorations
#include "zscript/TCOTDSwitchableDecoration/TCOTDSwitchableDecoration.zc"
#include "zscript/TCOTDFireMixin/TCOTDFireMixin.zc"
#include "zscript/TCOTDFireSpawner/TCOTDFireSpawner.zc"
#include "zscript/TCOTDWallTorch/TCOTDWallTorch.zc"
#include "zscript/TCOTDStreetLamp/TCOTDStreetLamp.zc"
#include "zscript/TCOTDMinotaurTorch/TCOTDMinotaurTorch.zc"
#include "zscript/TCOTDTallTorch/TCOTDTallTorch.zc"
#include "zscript/TCOTDInteractiveSwitchableDecoration/TCOTDInteractiveSwitchableDecoration.zc"
#include "zscript/TCOTDCandelabra/TCOTDCandelabra.zc"
#include "zscript/TCOTDCandle/TCOTDCandle.zc"
#include "zscript/TCOTDProp/TCOTDProp.zc"
#include "zscript/TCOTDFlatProp/TCOTDFlatProp.zc"
#include "zscript/TCOTDExplosiveBarrel/TCOTDExplosiveBarrel.zc"
#include "zscript/TCOTDPushPuzz/TCOTDPushPuzz.zc"
#include "zscript/TCOTDMoon/TCOTDMoon.zc"
#include "zscript/TCOTDFlare/TCOTDFlare.zc"

// Dynamic Clutter
#include "zscript/TCOTDClutterHandler/TCOTDClutterHandler.zc"
#include "zscript/TCOTDClutterThinker/TCOTDClutterThinker.zc"

// Foliage
#include "zscript/TCOTDFoliage/TCOTDFoliage.zc"

// Trees
#include "zscript/TCOTDTree/TCOTDTree.zc"

// Player
#include "zscript/TCOTDPlayer/TCOTDPlayer.zc"
#include "zscript/TCOTDPlayerHandler/TCOTDPlayerHandler.zc"

// Monsters
#include "zscript/TCOTDMonster/TCOTDMonster.zc"
#include "zscript/TCOTDMonster/TCOTDCultist.zc"

// Weapons and Ammo
#include "zscript/TCOTDWeapon/TCOTDWeapon.zc"
#include "zscript/TCOTDWeapon/TCOTDWeaponMelee.zc"
#include "zscript/TCOTDWeapon/TCOTDWeaponRevolver.zc"
#include "zscript/TCOTDWeapon/TCOTDWeaponSawedOff.zc"
#include "zscript/TCOTDWeapon/TCOTDWeaponThompson.zc"
#include "zscript/TCOTDWeapon/TCOTDWeaponNapalmLauncher.zc"
#include "zscript/TCOTDAmmo/TCOTDAmmo.zc"
#include "zscript/TCOTDBulletPuff/TCOTDBulletPuff.zc"
#include "zscript/TCOTDEmptyCasing/TCOTDEmptyCasing.zc"

// Misc
#include "zscript/TCOTDExMark/TCOTDExMark.zc"
#include "zscript/TCOTDMoonShelterMarker/TCOTDMoonShelterMarker.zc"

// HUD
#include "zscript/TCOTDHUD/TCOTDHUD.zc"
