version "4.10"

// Actor that does the bare minimum of ticking VARIANT, different from DietActor - Use for static, non-interactive actors, derived from bits and pieces of p_mobj.cpp
class SimpleActor : Actor
{
	Vector2 floorxy;
	Vector3 oldpos;

	override void Tick()
	{
		if (IsFrozen()) { return; }

		Vector2 curfloorxy = (curSector.GetXOffset(sector.floor), curSector.GetYOffset(sector.floor)); // Hacky scroll check because MF8_INSCROLLSEC not externalized to ZScript?
		bool dotick = (curfloorxy != floorxy) || curSector.flags & sector.SECF_PUSH || (pos != oldpos);

		if (dotick) // Only run a full Tick once; or if we are on a carrying floor, pushers are enabled in the sector (wind), or if we moved by some external force
		{
			oldpos = pos;
			Super.Tick();
			floorxy = curfloorxy;
			return;
		}

		if (vel != (0, 0, 0)) // Apply velocity as required
		{
			SetXYZ(Vec3Offset(vel.X, vel.Y, vel.Z)); // Vec3Offset is portal-aware; use instead of just pos + vel, which is not
		}

		// Tick through actor states as normal
		if (tics == -1) { return; }
		else if (--tics <= 0)
		{
			SetState(CurState.NextState);
		}
	}
}

class ParticleBase : SimpleActor
{
	int checktimer;
	int flags;

	FlagDef CHECKPOSITION:flags, 0;

	States
	{
		Fade:
			"####" "#" 1 A_FadeOut(0.1, FTF_REMOVE);
			Loop;
	}

	override void PostBeginPlay()
	{
		Super.PostBeginPlay();

		// Set the initial check at a random tick so they don't all check at once...
		checktimer = Random(0, 35);
	}

	override void Tick()
	{
		Super.Tick();

		if (bCheckPosition && checktimer-- <= 0)
		{
			// If it's outside the level, remove it
			if (!level.IsPointInLevel(pos)) { Destroy(); return; }

			checktimer = 35; // Check once every second.
		}
	}
}

// Core
#include "zscript/core/constants.zc"
#include "zscript/core/INIFile.zc"
#include "zscript/core/TCOTDGameplayStatics.zc"
#include "zscript/core/TCOTDDietActor.zc"
#include "zscript/core/TCOTDClientsideOnlyMixin.zc"
#include "zscript/core/TCOTDFloaterDetector.zc"

// Sound
#include "zscript/player/TCOTDSoundPlayer.zc"
#include "zscript/player/TCOTDFootstep.zc"
#include "zscript/props/TCOTDSiren.zc"

// Items
#include "zscript/items/TCOTDHealthPickup.zc"
#include "zscript/items/TCOTDLanternPickup.zc"
#include "zscript/items/TCOTDLanternOilPickup.zc"
#include "zscript/items/TCOTDPendant.zc"
#include "zscript/keys/TCOTDKey.zc"
#include "zscript/items/TCOTDPuzzle.zc"
#include "zscript/items/TCOTDArmor.zc"

// Bumi (stripped down to snow effects only)
#include "zscript/core/TCOTDWeatherHandler.zc"
#include "zscript/effects/TCOTDSnowParticle.zc"

// Weather FX
#include "zscript/props/TCOTDFogCloud.zc"

// Props and Decorations
#include "zscript/props/TCOTDSwitchableDecoration.zc"
#include "zscript/props/TCOTDFireMixin.zc"
#include "zscript/props/TCOTDFireSpawner.zc"
#include "zscript/props/TCOTDWallTorch.zc"
#include "zscript/props/TCOTDStreetLamp.zc"
#include "zscript/props/TCOTDMinotaurTorch.zc"
#include "zscript/props/TCOTDTallTorch.zc"
#include "zscript/props/TCOTDInteractiveSwitchableDecoration.zc"
#include "zscript/props/TCOTDCandelabra.zc"
#include "zscript/props/TCOTDCandle.zc"
#include "zscript/props/TCOTDProp.zc"
#include "zscript/props/TCOTDFlatProp.zc"
#include "zscript/props/TCOTDExplosiveBarrel.zc"
#include "zscript/props/TCOTDPushPuzz.zc"
#include "zscript/props/TCOTDMoon.zc"
#include "zscript/props/TCOTDSOSFlare.zc"

// Dynamic Clutter
#include "zscript/core/TCOTDClutterHandler.zc"
#include "zscript/core/TCOTDClutterThinker.zc"

// Foliage
#include "zscript/props/TCOTDFoliage.zc"

// Trees
#include "zscript/props/TCOTDTree.zc"

// Player
#include "zscript/player/TCOTDPlayer.zc"
#include "zscript/player/TCOTDPlayerHandler.zc"

// Monsters
#include "zscript/monsters/TCOTDMonster.zc"
#include "zscript/monsters/TCOTDApprentice.zc"
#include "zscript/monsters/TCOTDBeast.zc"
#include "zscript/monsters/TCOTDButcher.zc"
#include "zscript/monsters/TCOTDCultist.zc"
#include "zscript/monsters/TCOTDESoul.zc"
#include "zscript/monsters/TCOTDGhoul.zc"
#include "zscript/monsters/TCOTDHand.zc"
#include "zscript/monsters/TCOTDHarvest.zc"
#include "zscript/monsters/TCOTDHotdog.zc"
#include "zscript/monsters/TCOTDIncarnate.zc"
#include "zscript/monsters/TCOTDMinispider.zc"
#include "zscript/monsters/TCOTDNitemare.zc"
#include "zscript/monsters/TCOTDShadow.zc"
#include "zscript/monsters/TCOTDTchernobog.zc"
#include "zscript/monsters/TCOTDThamuzBog.zc"
#include "zscript/monsters/TCOTDThrall.zc"
#include "zscript/monsters/TCOTDVulgar.zc"
#include "zscript/monsters/TCOTDWraith.zc"
#include "zscript/monsters/TCOTDZombie.zc"

// Weapons and Ammo
#include "zscript/weapons/TCOTDWeapon.zc"
#include "zscript/weapons/TCOTDWeaponMelee.zc"
#include "zscript/weapons/TCOTDWeaponRevolver.zc"
#include "zscript/weapons/TCOTDWeaponSawedOff.zc"
#include "zscript/weapons/TCOTDWeaponThompson.zc"
#include "zscript/weapons/TCOTDWeaponNapalmLauncher.zc"
#include "zscript/weapons/TCOTDAmmo.zc"
#include "zscript/effects/TCOTDBulletPuff.zc"
#include "zscript/effects/TCOTDEmptyCasing.zc"

// Blood & Gore
#include "zscript/gore/TCOTDBlood.zc"
#include "zscript/gore/TCOTDGib.zc"

// Misc
#include "zscript/effects/TCOTDExMark.zc"
#include "zscript/mapmarkers/TCOTDMoonShelterMarker.zc"
#include "zscript/TCOTDOthers/deathmusicplayer.zc"
#include "zscript/TCOTDOthers/heateffect.zc"
#include "zscript/TCOTDOthers/mblur.zc"
#include "zscript/effects/swirl.zc" //from BoA
#include "zscript/effects/splashes.zc"
#include "zscript/effects/smoke.zc"
#include "zscript/misc/TCOTDCutsceneCamera.zc"
#include "zscript/misc/TCOTDCivilian.zc"

// HUD
#include "zscript/UI/HUD/TCOTDAltHUD.zc"
#include "zscript/UI/HUD/TCOTDHUD.zc"

// Underwater
#include "zscript/TCOTDOthers/underwater.zc"
