version "4.3.3"

class StrongholdEventHandler : StaticEventHandler
{
	//===========================================================================
	// HEAT SHADER EVENTHANDLERS
	//===========================================================================
	override void RenderOverlay(RenderEvent e)
	{
		PlayerInfo p = players[consoleplayer];
		ThinkerIterator shaderIter = ThinkerIterator.Create("ShaderControl");

		ShaderControl shaderControl;

		while (shaderControl = ShaderControl(shaderIter.Next()))
		{
			if (shaderControl.Owner && shaderControl.Owner == p.mo) {
				//Console.Printf("Shader: %s", shaderControl.ShaderToControl);
				if (shaderControl.amount >= 2)
				{
					Shader.SetUniform1f(p, shaderControl.ShaderToControl, "timer", gametic + e.FracTic);
					Shader.SetUniform1f(p, shaderControl.ShaderToControl, "amount", shaderControl.amount - 1);
					Shader.SetUniform1f(p, shaderControl.ShaderToControl, "alpha", shaderControl.alpha);
					shaderControl.SetUniforms(p, e);
					Shader.SetEnabled(p, shaderControl.ShaderToControl, true);
				}
				else
				{
					Shader.SetEnabled(p, shaderControl.ShaderToControl, false);
				}
			}
		}
	}

	//===========================================================================
	// INVENTORY EVENTHANDLERS
	//===========================================================================
	override void PlayerEntered(PlayerEvent e)
	{
		let me=PlayerPawn(players[e.PlayerNumber].mo);
		DropItem drop=me.GetDropItems();
		//First, remove all weapons, except those with the UNDROPPABLE flag
		for(int i=0;i<AllActorClasses.Size();i++)
		{
			let type=AllActorClasses[i];
			if(type is "Weapon")
			{
				let weptype=(class<weapon>)(type);
				let wepitem=weapon(me.FindInventory(weptype));
				if(wepitem!=null&&!wepitem.bUNDROPPABLE)
					me.A_TakeInventory(name(weptype));
			}
		}
		//If the player has any weapons in StartItem, set them here
		//They're not supposed to come with ammo, so clear that after this
		if(drop!=null)
		{
			for(DropItem di=drop;di!=null;di=di.Next)
			{
				if(di.Name=='None')
					continue;
				let weptype=(class<weapon>)(di.Name);
				if(weptype!=null)
					me.A_SetInventory(di.Name,di.Amount);
			}
		}
		//Remove all ammo, except that with the UNDROPPABLE flag
		for(int i=0;i<AllActorClasses.Size();i++)
		{
			let type=AllActorClasses[i];
			if(type is "Ammo")
			{
				let ammotype=(class<ammo>)(type);
				let ammoitem=ammo(me.FindInventory(ammotype));
				if(ammoitem!=null&&!ammoitem.bUNDROPPABLE)
					me.A_TakeInventory(name(ammotype));
			}
		}
		//If the player has any ammo in StartItem, set it here
		if(drop!=null)
		{
			for(DropItem di=drop;di!=null;di=di.Next)
			{
				if(di.Name=='None')
					continue;
				let ammotype=(class<ammo>)(di.Name);
				if(ammotype!=null)
					me.A_SetInventory(di.Name,di.Amount);
			}
		}
	}
}

#include "zscript/SthProps.zc" 	//RichardDS90/Salahmander
#include "zscript/Sthcasing.zc"
#include "zscript/SthTorch.zc"
#include "zscript/SthFX.zc"
#include "zscript/mblur.zc"
#include "zscript/underwater.zc"
#include "zscript/heateffect.zc"
#include "zscript/StrongholdCosmeticActors.zc"

#include "zscript/converted/decorate.zc"
#include "zscript/converted/torch.zc"
#include "zscript/converted/sfx_water.zc"
#include "zscript/converted/sfx_rain.zc"
#include "zscript/converted/sfx_snow.zc"
#include "zscript/converted/dec_player.zc"
#include "zscript/converted/dec_weapons.zc"
#include "zscript/converted/dec_item.zc"
#include "zscript/converted/monsters/doom.zc"
#include "zscript/converted/monsters/bruiserdemon.zc"
#include "zscript/converted/monsters/archonofhell.zc"
#include "zscript/converted/monsters/azazel.zc"
#include "zscript/converted/monsters/blooddemon.zc"
#include "zscript/converted/monsters/catharsi.zc"
#include "zscript/converted/monsters/cybruiser.zc"
#include "zscript/converted/monsters/demolisher.zc"
#include "zscript/converted/monsters/diabolist.zc"
#include "zscript/converted/monsters/dunewarrior.zc"
#include "zscript/converted/monsters/enhcaco.zc"
#include "zscript/converted/monsters/fusionspider.zc"
#include "zscript/converted/monsters/gcube.zc"
#include "zscript/converted/monsters/hectebus.zc"
#include "zscript/converted/monsters/helemental.zc"
#include "zscript/converted/monsters/hellion.zc"
#include "zscript/converted/monsters/hellwarrior.zc"
#include "zscript/converted/monsters/shadow.zc"
#include "zscript/converted/monsters/rockettrooper.zc"
#include "zscript/converted/monsters/suicide.zc"
#include "zscript/converted/monsters/nightmarecaco.zc"
#include "zscript/converted/monsters/nightmaredemon.zc"
#include "zscript/converted/monsters/pyrodemon.zc"
#include "zscript/converted/monsters/overmind.zc"
#include "zscript/converted/monsters/terminator.zc"
#include "zscript/converted/monsters/ztank.zc"
#include "zscript/converted/monsters/wicked.zc"
#include "zscript/converted/monsters/phaseimp.zc"
#include "zscript/converted/monsters/bigboss.zc"
#include "zscript/converted/monsters/moloch.zc"
#include "zscript/converted/monsters/infernodemon.zc"
#include "zscript/converted/monsters/satyr.zc"
#include "zscript/converted/monsters/plasmazombie.zc"
#include "zscript/converted/dec_morp.zc"
#include "zscript/converted/nashgore.zc"
#include "zscript/converted/critters.zc"
#include "zscript/converted/holo.zc"
#include "zscript/converted/npcs.zc"
#include "zscript/converted/models.zc"
#include "zscript/converted/duke3d.zc"
#include "zscript/converted/cityofsilence.zc"
#include "zscript/converted/disco.zc"
#include "zscript/converted/exclamation.zc"
#include "zscript/converted/scoreboard.zc"
#include "zscript/converted/skybeams.zc"
#include "zscript/converted/splashes.zc"
#include "zscript/converted/hudstuff.zc"
