"""Define eight normalized grass sprites without modifying generated RGBA artwork."""
from pathlib import Path
import argparse
from PIL import Image
ROOT=Path(__file__).resolve().parent.parent
def generate(root=ROOT,check=False):
    rows=['// Generated by tools/build_grass_sprites.py; original RGBA patches stay intact.']
    for i,c in enumerate('ABCDEFGH',1):
        path=root/f'tutnt/patches/grass/tuft-{i}.png'
        with Image.open(path) as im:
            if im.mode!='RGBA': raise ValueError(f'{path}: missing alpha')
            alpha=im.getchannel('A')
            if alpha.getextrema()!=(0,255): raise ValueError(f'{path}: expected transparent and opaque pixels')
            box=alpha.point(lambda a:255 if a>=96 else 0).getbbox()
            if not box: raise ValueError(f'{path}: empty sprite')
        l,t,r,b=box;w,h=r-l,b-t
        rows.append(f'Sprite GRSU{c}0, {w}, {h}\n{{\n Offset {w//2}, {h}\n XScale {h/96:.10f}\n YScale {h/96:.10f}\n Patch "patches/grass/tuft-{i}.png", {-l}, {-t}\n}}\n')
    rows += [row.replace('Sprite GRSU','Sprite GRSV') for row in rows[1:]]
    target=root/'tutnt/textures/definitions/TEXTURES.grass'
    text='\n'.join(rows).rstrip()+'\n'
    if check:
        if target.read_text()!=text: raise ValueError('Grass sprite definitions are stale')
    else: target.write_text(text)
    return 8
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true')
    print(f'{generate(check=p.parse_args().check)} grass sprite definitions verified')
