"""Build native Source materials from existing SOURA0 and RUNE1..9 assets.

No raster asset is redrawn or generated. TEXTURES assembles the original glyphs,
and the material performs the ring placement and state-specific deformation.
"""
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent

SPRITES={'USC0A0':0,'USC1A0':1,'USRCA0':2,'USROA0':3,'USREA0':4,
         'USHEA0':5,'USORA0':6,'USRIPA0':7,'USSTA0':8,'USLNA0':9,'USDFA0':10}

def build(root=ROOT):
 root=Path(root);t=root/'tutnt';out=t/'shaders/sourcefx';out.mkdir(parents=True,exist_ok=True)
 textures=['// Original assets, assembled by the engine; no duplicated rune artwork.',
           'Texture USRUNES, 288, 32 {']
 textures += [f' Patch "RUNE{i+1}", {32*i}, 0' for i in range(9)]
 textures+=['}']
 defs=[];sprite=(root/'tools/source-sprite.glsl').read_text()
 for name,kind in SPRITES.items():
  textures += [f'Sprite {name}, 512, 512 {{ Offset 256, 256 Patch "SOURA0", 0, 0 }}']
  shader=f'shaders/sourcefx/{name.lower()}.fp'
  (t/shader).write_text(f'// Generated by tools/build_source_materials.py\n#define SOURCE_KIND {kind}\n'+sprite)
  defs += [f'Material Sprite "{name}" {{ Shader "{shader}" Texture runeAtlas "USRUNES" }}']
 beam=(root/'tools/source-beam.glsl').read_text()
 for kind,asset in enumerate(['T4_BM1','T4_BM2','T4_BM2B']):
  w,h=(768,64) if kind==0 else (1500,512)
  for state in range(3):
   name=f'USB{kind}{state}';shader=f'shaders/sourcefx/{name.lower()}.fp'
   textures += [f'Texture {name}, {w}, {h} {{ Patch "{asset}", 0, 0 }}']
   (t/shader).write_text(f'// Generated by tools/build_source_materials.py\n#define BEAM_KIND {kind}\n#define BEAM_STATE {state}\n'+beam)
   defs += [f'Material Texture "{name}" {{ Shader "{shader}" }}']
 textures += ['Texture USSHIELD, 512, 512 { Patch "SOURA0", 0, 0 }']
 (out/'shield.fp').write_text((root/'tools/source-shield.glsl').read_text())
 defs += ['Material Texture "USSHIELD" { Shader "shaders/sourcefx/shield.fp" Texture runeAtlas "USRUNES" }']
 (t/'TEXTURES.source').write_text('\n'.join(textures)+'\n')
 (t/'GLDEFS.source').write_text('\n'.join(defs)+'\n')

if __name__=='__main__':build()
