"""Generate explicit CRT glass bindings. Original diffuse/animation data is never changed."""
from pathlib import Path
import argparse,json,io
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
def generate(root=ROOT,check=False):
 root=Path(root); config=json.loads((root/'tools/crt-materials.json').read_text())
 names=[];blocks=['// Generated by tools/build_crt_materials.py.'];images={}
 for item in config['screens']:
  name=item['name'];w,h=item['size'];rects=item['glass']
  assert name not in names and not name.startswith('CAM_T'),name
  assert 0<len(rects)<=3
  for x0,y0,x1,y1 in rects:assert 0<=x0<x1<=w and 0<=y0<y1<=h,(name,rects)
  names.append(name)
  definitions={'CRT_SIZE':f'vec2({w}.0,{h}.0)','CRT_BULGE':str(float(item.get('bulge',.0825))),'CRT_COUNT':str(len(rects)),'CRT_SCAN_X':str(int(item.get('scan_x',False))),'CRT_LIT':str(float(item.get('lit',1)))}
  for i,r in enumerate(rects+[[0,0,1,1]]*(3-len(rects))):
   definitions['CRT_RECT'+str(i)]='vec4('+','.join(str(float(v)) for v in r)+')'
  # Native white/black brightmap: fullbright glass, normally lit housing.
  bright=Image.new('RGB',(w,h),(0,0,0))
  for x0,y0,x1,y1 in rects:
   for y in range(y0,y1):
    for x in range(x0,x1):
     gx=abs(2*(x+.5-x0)/(x1-x0)-1);gy=abs(2*(y+.5-y0)/(y1-y0)-1)
     if max(gx-.91,0)**2+max(gy-.91,0)**2<=.09**2:bright.putpixel((x,y),(255,255,255))
  encoded=io.BytesIO();bright.save(encoded,format='PNG',compress_level=9)
  brightpath='materials/crt/brightmaps/'+name.lower()+'.png'
  images['tutnt/'+brightpath]=encoded.getvalue()
  b=['Material "'+name+'" {',' Shader "shaders/crt/screen.fp"']
  b+=[' Define '+k+' = "'+v+'"' for k,v in definitions.items()]
  b+=[' Brightmap "'+brightpath+'"',' Texture crtState "UCRTSTAT"',' Texture crtProbe0 "UCRTP0"',' Texture crtProbe1 "UCRTP1"','}']
  blocks.append('\n'.join(b))
 outputs={'tutnt/gldefs/GLDEFS.crt':'\n\n'.join(blocks)+'\n','tutnt/materials/crt/screens.txt':'|'.join(['']+names+[''])}
 for name,data in outputs.items():
  path=root/name
  if check:
   if not path.exists() or path.read_text()!=data:raise ValueError('Stale CRT output: '+name)
  elif not path.exists() or path.read_text()!=data:
   path.parent.mkdir(parents=True,exist_ok=True);path.write_text(data,encoding='utf-8',newline='\n')
 for name,data in images.items():
  path=root/name
  if check:
   if not path.exists() or path.read_bytes()!=data:raise ValueError('Stale CRT brightmap: '+name)
  elif not path.exists() or path.read_bytes()!=data:
   path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(data)
 return {'brightmaps':len(images),'screens':len(names),'excluded':'CAM_T*','ok':True}
if __name__=='__main__':
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args();print(json.dumps(generate(check=a.check)))
