"""Generate explicit CRT glass bindings. Original diffuse/animation data is never changed."""
from pathlib import Path
import argparse,json
ROOT=Path(__file__).resolve().parents[1]
def generate(root=ROOT,check=False):
 root=Path(root); config=json.loads((root/'tools/crt-materials.json').read_text())
 names=[];blocks=['// Generated by tools/build_crt_materials.py.']
 for item in config['screens']:
  name=item['name'];w,h=item['size'];rects=item['glass']
  assert name not in names and not name.startswith('CAM_T'),name
  assert 0<len(rects)<=3
  for x0,y0,x1,y1 in rects:assert 0<=x0<x1<=w and 0<=y0<y1<=h,(name,rects)
  names.append(name)
  definitions={'CRT_SIZE':f'vec2({w}.0,{h}.0)','CRT_BULGE':str(float(item.get('bulge',.055))),'CRT_COUNT':str(len(rects)),'CRT_SCAN_X':str(int(item.get('scan_x',False))),'CRT_LIT':str(float(item.get('lit',1)))}
  for i,r in enumerate(rects+[[0,0,1,1]]*(3-len(rects))):
   definitions['CRT_RECT'+str(i)]='vec4('+','.join(str(float(v)) for v in r)+')'
  b=['Material "'+name+'" {',' Shader "shaders/crt/screen.fp"']
  b+=[' Define '+k+' = "'+v+'"' for k,v in definitions.items()]
  b+=[' Texture crtState "UCRTSTAT"',' Texture crtProbe0 "UCRTP0"',' Texture crtProbe1 "UCRTP1"','}']
  blocks.append('\n'.join(b))
 outputs={'tutnt/gldefs/GLDEFS.crt':'\n\n'.join(blocks)+'\n','tutnt/materials/crt/screens.txt':'|'.join(['']+names+[''])}
 for name,data in outputs.items():
  path=root/name
  if check:
   if not path.exists() or path.read_text()!=data:raise ValueError('Stale CRT output: '+name)
  elif not path.exists() or path.read_text()!=data:
   path.parent.mkdir(parents=True,exist_ok=True);path.write_text(data,encoding='utf-8',newline='\n')
 return {'screens':len(names),'excluded':'CAM_T*','ok':True}
if __name__=='__main__':
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args();print(json.dumps(generate(check=a.check)))
