"""Compile approved deadwood art to native Doom patches using UTNT PLAYPAL.

Decode only the explicit chroma key, separate the six subjects, reduce to the
original sprite pixel density, and quantize without dithering. Native patch
indices follow the engine's active PLAYPAL at runtime. No map is modified.
"""
from pathlib import Path
import argparse, hashlib, json, struct
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ART = Path("tools/artwork/deadwood")
PATCHES = Path("tutnt/patches/deadwood")
DEFINITIONS = Path("tutnt/textures/definitions/TEXTURES.deadwood")


def write(path, data, check):
    if path.exists() and path.read_bytes() == data:
        return
    if check:
        raise ValueError(f"Stale or missing deadwood output: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def encode_patch(indices, visible, left, top):
    h,w = indices.shape
    if not 0 < h < 255:
        raise ValueError("Native deadwood frames must fit ordinary Doom posts")
    columns=[];offsets=[];offset=8+4*w
    for x in range(w):
        column=bytearray();y=0
        while y<h:
            if not visible[y,x]:
                y+=1;continue
            start=y
            while y<h and visible[y,x]:y+=1
            column.extend(bytes((start,y-start,0)))
            column.extend(indices[start:y,x].tobytes())
            column.append(0)
        column.append(255);offsets.append(offset);offset+=len(column);columns.append(column)
    return struct.pack("<hhhh",w,h,left,top)+struct.pack("<"+"I"*w,*offsets)+b"".join(columns)


def decode_patch(data):
    w,h,left,top=struct.unpack_from("<hhhh",data)
    indices=np.zeros((h,w),dtype=np.uint8);visible=np.zeros((h,w),dtype=bool)
    for x in range(w):
        p=struct.unpack_from("<I",data,8+x*4)[0]
        while data[p]!=255:
            y,n=data[p],data[p+1]
            indices[y:y+n,x]=np.frombuffer(data[p+3:p+3+n],dtype=np.uint8)
            visible[y:y+n,x]=True;p+=n+4
    return indices,visible,(left,top)


def generate(root=ROOT, check=False):
    root=Path(root)
    config=json.loads((root/ART/"atlas-layout.json").read_text())
    palette=(root/ART/"quantization.pal").read_bytes()
    if len(palette)!=768:raise ValueError("Expected the base 256-color PLAYPAL")
    profiles_config=json.loads((root/ART/"palette-profiles.json").read_text())
    palette_rgb=np.frombuffer(palette,dtype=np.uint8).reshape(256,3)
    definitions=["// Generated by tools/build_deadwood_sprites.py; native PLAYPAL sprites.\n"]
    report=[]
    for family in config["families"]:
        source=root/ART/(family["name"]+"-key.png")
        rgb=np.asarray(Image.open(source).convert("RGB"))
        r,g,b=(rgb[:,:,i].astype(np.int16) for i in range(3))
        key=(r>g+8)&(b>g+8)
        if key.mean()<.30 or not all(key[y,x] for x,y in [(0,0),(-1,0),(0,-1),(-1,-1)]):
            raise ValueError(f"{source}: missing clean chroma-key background")
        alpha=np.where(key,0,255).astype(np.uint8)
        for i,(x0,y0,x1,y1) in enumerate(family["cells"]):
            cell_alpha=alpha[y0:y1,x0:x1].copy()
            for ax,ay,bx,by in family.get("exclude",{}).get(str(i),[]):
                cell_alpha[ay-y0:by-y0,ax-x0:bx-x0]=0
            bbox=Image.fromarray(cell_alpha).getbbox()
            if not bbox:raise ValueError(f"{source}: empty cell {i}")
            left,top,right,bottom=bbox
            if left<2 or top<2 or right>x1-x0-2 or bottom>y1-y0-2:
                raise ValueError(f"{source}: cell {i} touches a cut boundary")
            x,y,w,h=x0+left,y0+top,right-left,bottom-top
            frame="ABC"[i%3];is_tree=i<3
            # Doom's TRE2 is 124px high; the original icy tree is 127px.
            # Stumps use a small 40px grid shared with the 33-unit icy view.
            native_h=(127 if family["name"]=="frozen" else 124) if is_tree else 40
            native_w=max(1,round(w*native_h/h))
            rgba=np.dstack((rgb[y:y+h,x:x+w],cell_alpha[top:bottom,left:right]))
            rgba[rgba[:,:,3]==0,:3]=0
            reduced=Image.fromarray(rgba).resize((native_w,native_h),Image.Resampling.BOX)
            visible=np.asarray(reduced.getchannel("A"))>=96
            # Match the matte value range and color ramps of the original props.
            profile=profiles_config[family["name"]]
            colors=np.asarray(reduced.convert("RGB"))
            toned=np.rint(colors.astype(float)*profile["exposure"]).astype(np.int32)
            allowed=np.array(profile["indices"],dtype=np.uint8)
            flat=toned.reshape(-1,3);nearest=np.empty(len(flat),dtype=np.uint8)
            for start in range(0,len(flat),4096):
                distance=((flat[start:start+4096,None,:]-palette_rgb[allowed].astype(np.int32)[None,:,:])**2).sum(axis=2)
                nearest[start:start+4096]=allowed[distance.argmin(axis=1)]
            indices=nearest.reshape(native_h,native_w)
            # Preserve only the approved tiny ember fissure, never warm bark flecks.
            if family["name"]=="charred" and i==5:
                ember=(colors[:,:,0]>colors[:,:,1]*1.8)&(colors[:,:,1]>25)&(colors[:,:,0]>150)&visible
                for yy,xx in zip(*np.where(ember)):
                    distance=((palette_rgb.astype(np.int32)-colors[yy,xx].astype(np.int32))**2).sum(axis=1)
                    indices[yy,xx]=distance.argmin()
            anchor=round((family["anchors"][i]-x)*native_w/w)
            encoded=encode_patch(indices,visible,anchor,native_h)
            decoded,mask,offset=decode_patch(encoded)
            if not np.array_equal(mask,visible) or not np.array_equal(decoded[mask],indices[mask]) or offset!=(anchor,native_h):
                raise ValueError("Doom patch round-trip lost pixels, transparency or offsets")
            patch_name=family["name"]+("-tree-" if is_tree else "-stump-")+frame.lower()+".lmp"
            write(root/PATCHES/patch_name,encoded,check)
            profiles=[(family["prefix"]+("T" if is_tree else "S"),124 if is_tree else 40)]
            if family["name"]=="frozen":
                profiles.append(("DWIT" if is_tree else "DWIS",127 if is_tree else 33))
            for prefix,height in profiles:
                scale=native_h/height
                definitions.append(f'Sprite {prefix}{frame}0, {native_w}, {native_h}\n{{\n'
                    f' Offset {anchor}, {native_h}\n XScale {scale:.12g}\n YScale {scale:.12g}\n'
                    f' Patch "patches/deadwood/{patch_name}", 0, 0\n}}\n')
                report.append({"sprite":prefix+frame+"0","source":source.relative_to(root).as_posix(),
                    "source_bounds":[x,y,w,h],"native_size":[native_w,native_h],"anchor":[anchor,native_h],
                    "world_size":[native_w/scale,height],"palette_indices":len(np.unique(indices[visible])),
                    "quantization_palette_sha256":hashlib.sha256(palette).hexdigest()})
    write(root/DEFINITIONS,("\n".join(definitions).rstrip()+"\n").encode(),check)
    write(root/ART/"generated.json",(json.dumps(report,indent=2)+"\n").encode(),check)
    print(f"Deadwood: {len(report)} native PLAYPAL sprite views from 18 designs; {'verified' if check else 'generated'}")
    return report


if __name__=="__main__":
    p=argparse.ArgumentParser(description=__doc__);p.add_argument("--check",action="store_true")
    a=p.parse_args();generate(check=a.check)
