"""Compile approved liquid height artwork into matching height/normal assets.

The source PNGs are scalar art inputs. This compiler derives normal vectors,
never paints lighting into them. Python 3.11+, Pillow and NumPy are required.
"""
from pathlib import Path
import argparse, json, hashlib
import numpy as np
from PIL import Image, ImageFilter

ROOT=Path(__file__).resolve().parent.parent
FAMILIES={
 'water':(['QWATER1','QWATER2','QWATER3','QWATER3A','QFWAT'],10.0,0),
 'slime':(['QSLIME1','QSLIME2','IKSLIME1','IKSLIME2','SLIME05B'],14.0,1),
 'blood':(['QWATERT6'],9.0,2),
}

def build(root=ROOT):
    root=Path(root)
    materials=root/'tutnt/materials/liquids';materials.mkdir(parents=True,exist_ok=True)
    shaders=root/'tutnt/shaders/liquids';shaders.mkdir(parents=True,exist_ok=True)
    common=(root/'tools/liquid-surface.glsl').read_text()
    records={};defs=['// Generated by tools/build_liquid_assets.py. Original flats remain the software fallback.']
    for family,(names,height,kind) in FAMILIES.items():
        image=Image.open(root/f'tools/artwork/liquids/{family}-source.png').convert('L').resize((1024,1024),Image.Resampling.LANCZOS)
        # Explicit prefiltered scalar channels also work with OpenGL's nearest
        # sampler, where hardware mip levels may not be allocated.
        Image.merge('RGB',(image,image.filter(ImageFilter.GaussianBlur(2.0)),image.filter(ImageFilter.GaussianBlur(12.0)))).save(materials/f'{family}-height.png')
        a=np.asarray(image,dtype=np.float32)/255.
        dy,dx=np.gradient(a,384./1024)
        dx*=height;dy*=height
        normal=np.stack((-dx,-dy,np.ones_like(a)),axis=-1)
        normal/=np.linalg.norm(normal,axis=-1,keepdims=True)
        encoded=np.rint(np.clip(normal*.5+.5,0,1)*255).astype(np.uint8)
        Image.fromarray(encoded).save(materials/f'{family}-normal.png')
        (shaders/f'{family}.fp').write_text(f'// Generated from tools/liquid-surface.glsl\n#define LIQUID_KIND {kind}\n#define LIQUID_DEPTH {height:.3f}\n'+common)
        for name in names:
            defs.append(f'''Material Flat "{name}"
{{
    Shader "shaders/liquids/{family}.fp"
    Normal "materials/liquids/{family}-normal.png"
    Specular "materials/liquids/specular.png"
    Texture liquidHeight "materials/liquids/{family}-height.png"
    Speed 1.0
}}''')
        records[family]={'size':[1024,1024],'height_units':height,'height_range':[float(a.min()),float(a.max())],
            'normal_max_unit_error':float(np.abs(np.linalg.norm(encoded.astype(float)/255*2-1,axis=-1)-1).max()),
            'source_sha256':hashlib.sha256((root/f'tools/artwork/liquids/{family}-source.png').read_bytes()).hexdigest()}
    Image.new('RGB',(1,1),(255,255,255)).save(materials/'specular.png')
    # Legacy names are declared in ANIMDEFS but have no assets or map uses in UTNT.
    # Provide explicit conservative aliases so bindings also work for external maps.
    (root/'tutnt/TEXTURES.liquids').write_text('''// Missing legacy slime names, supplied as native-palette aliases.
Flat IKSLIME1, 64, 64 { Patch QSLIME1, 0, 0 }
Flat IKSLIME2, 64, 64 { Patch QSLIME2, 0, 0 }
''')
    cosmic=(root/'tools/liquid-cosmic.glsl').read_text()
    for name,kind in [('QTELEPT',0),('QTELEPOR',0),('STARSKY1',1),('STARSKY2',2)]:
        filename=name.lower()+'.fp'
        (shaders/filename).write_text(f'// Generated from tools/liquid-cosmic.glsl\n#define COSMIC_KIND {kind}\n'+cosmic)
        defs.append(f'Material {"Flat" if name=="QTELEPT" else "Texture"} "{name}"\n{{\n    Shader "shaders/liquids/{filename}"\n    Speed 1.0\n}}')
    (root/'tutnt/GLDEFS.liquids').write_text('\n\n'.join(defs)+'\n')
    (root/'tools/artwork/liquids/asset-manifest.json').write_text(json.dumps(records,indent=2)+'\n')
    print(json.dumps(records,indent=2))

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--root',type=Path,default=ROOT)
    build(p.parse_args().root)
