"""Compile approved native deadwood grids to Doom patches using active PLAYPAL.

Preserve reviewed pixel indices and transparency exactly, with explicit trunk
anchors and the original actor visual heights. No resampling or map edits.
"""
from pathlib import Path
import argparse, hashlib, json, struct
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ART = Path("tools/artwork/deadwood")
PATCHES = Path("tutnt/patches/deadwood")
DEFINITIONS = Path("tutnt/textures/definitions/TEXTURES.deadwood")


def write(path, data, check):
    if path.exists() and path.read_bytes() == data:
        return
    if check:
        raise ValueError(f"Stale or missing deadwood output: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def encode_patch(indices, visible, left, top):
    h,w = indices.shape
    if not 0 < h < 255:
        raise ValueError("Native deadwood frames must fit ordinary Doom posts")
    columns=[];offsets=[];offset=8+4*w
    for x in range(w):
        column=bytearray();y=0
        while y<h:
            if not visible[y,x]:
                y+=1;continue
            start=y
            while y<h and visible[y,x]:y+=1
            column.extend(bytes((start,y-start,0)))
            column.extend(indices[start:y,x].tobytes())
            column.append(0)
        column.append(255);offsets.append(offset);offset+=len(column);columns.append(column)
    return struct.pack("<hhhh",w,h,left,top)+struct.pack("<"+"I"*w,*offsets)+b"".join(columns)


def decode_patch(data):
    w,h,left,top=struct.unpack_from("<hhhh",data)
    indices=np.zeros((h,w),dtype=np.uint8);visible=np.zeros((h,w),dtype=bool)
    for x in range(w):
        p=struct.unpack_from("<I",data,8+x*4)[0]
        while data[p]!=255:
            y,n=data[p],data[p+1]
            indices[y:y+n,x]=np.frombuffer(data[p+3:p+3+n],dtype=np.uint8)
            visible[y:y+n,x]=True;p+=n+4
    return indices,visible,(left,top)


def generate(root=ROOT, check=False):
    root=Path(root)
    config=json.loads((root/ART/"atlas-layout.json").read_text())
    if config.get("format")!="approved-indexed-native-v1":
        raise ValueError("Expected approved indexed native artwork")
    palette=(root/ART/"quantization.pal").read_bytes()
    if len(palette)!=768:raise ValueError("Expected the 256-color authoring palette")
    profiles_config=json.loads((root/ART/"palette-profiles.json").read_text())
    definitions=["// Generated by tools/build_deadwood_sprites.py; native PLAYPAL sprites.\n"]
    report=[]
    for family in config["families"]:
        if len(family["frames"])!=6:
            raise ValueError("Each deadwood family needs three trees and three stumps")
        for i,entry in enumerate(family["frames"]):
            source=root/ART/entry["source"]
            with Image.open(source) as image:
                if image.mode!="P" or image.info.get("transparency")!=255 or bytes(image.getpalette())!=palette:
                    raise ValueError(f"{source}: expected indexed authoring palette and transparent index 255")
                pixels=np.asarray(image).copy()
            native_h,native_w=pixels.shape
            frame="ABC"[i%3];is_tree=i<3
            expected_h=(127 if family["name"]=="frozen" else 124) if is_tree else 40
            if native_h!=expected_h:
                raise ValueError(f"{source}: native height must remain {expected_h}")
            visible=pixels!=255
            if not visible.any():raise ValueError(f"{source}: empty approved frame")
            if not set(np.unique(pixels[visible])).issubset(profiles_config[family["name"]]["indices"]):
                raise ValueError(f"{source}: pixels outside approved palette ramp")
            indices=np.where(visible,pixels,0).astype(np.uint8)
            anchor,top=entry["anchor"]
            if not 0<=anchor<native_w or top!=native_h:
                raise ValueError(f"{source}: invalid trunk/floor anchor")
            encoded=encode_patch(indices,visible,anchor,top)
            decoded,mask,offset=decode_patch(encoded)
            if not np.array_equal(mask,visible) or not np.array_equal(decoded[mask],indices[mask]) or offset!=(anchor,top):
                raise ValueError("Doom patch round-trip lost pixels, transparency or offsets")
            patch_name=family["name"]+("-tree-" if is_tree else "-stump-")+frame.lower()+".lmp"
            write(root/PATCHES/patch_name,encoded,check)
            profiles=[(family["prefix"]+("T" if is_tree else "S"),124 if is_tree else 40)]
            if family["name"]=="frozen":
                profiles.append(("DWIT" if is_tree else "DWIS",127 if is_tree else 33))
            for prefix,height in profiles:
                scale=native_h/height
                definitions.append(f'Sprite {prefix}{frame}0, {native_w}, {native_h}\n{{\n'
                    f' Offset {anchor}, {native_h}\n XScale {scale:.12g}\n YScale {scale:.12g}\n'
                    f' Patch "patches/deadwood/{patch_name}", 0, 0\n}}\n')
                report.append({"sprite":prefix+frame+"0","source":source.relative_to(root).as_posix(),
                    "selected_option":family["selected_option"],
                    "native_size":[native_w,native_h],"anchor":[anchor,native_h],
                    "world_size":[native_w/scale,height],"palette_indices":len(np.unique(indices[visible])),
                    "native_pixel_sha256":hashlib.sha256(pixels.tobytes()).hexdigest(),
                    "quantization_palette_sha256":hashlib.sha256(palette).hexdigest()})
    write(root/DEFINITIONS,("\n".join(definitions).rstrip()+"\n").encode(),check)
    write(root/ART/"generated.json",(json.dumps(report,indent=2)+"\n").encode(),check)
    print(f"Deadwood: {len(report)} native PLAYPAL sprite views from 18 approved designs; {'verified' if check else 'generated'}")
    return report

if __name__=="__main__":
    p=argparse.ArgumentParser(description=__doc__);p.add_argument("--check",action="store_true")
    a=p.parse_args();generate(check=a.check)
