"""Reproduce the 12-triangle, six-plane light shaft without external assets."""
import argparse
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate(root=ROOT, check=False):
    # OBJ uses Y up. UZDoom compensates model pixel aspect; MODELDEF restores
    # the original sprite's 256x256 footprint and (128,17) attachment point.
    lines = ['# Six radial light slices; generated by tools/build_light_ray_model.py.', 's off']
    for i in range(6):
        a = math.pi*i/6
        for x, z in [(-128,17),(128,17),(128,-239),(-128,-239)]:
            lines.append(f'v {x*math.cos(a):.8f} {z:.8f} {x*math.sin(a):.8f}')
    lines += ['vt 0 1','vt 1 1','vt 1 0','vt 0 0']
    for i in range(6):
        j = i*4+1
        lines += [f'f {j}/1 {j+1}/2 {j+2}/3', f'f {j}/1 {j+2}/3 {j+3}/4']
    data = '\n'.join(lines)+'\n'
    path = root/'tutnt/models/light-rays/shaft.obj'
    if check:
        if not path.exists() or path.read_text() != data:
            raise ValueError(f'Stale light-ray model: {path}')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(data, encoding='utf-8')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    generate(check=parser.parse_args().check)
