"""Build native Source materials from SOURA0 and the shared QRUNT63 rune atlas.

Native artwork stays unchanged. Tiny generated data/carrier images let the
materials share shader programs while retaining the original logical dimensions.
"""
from pathlib import Path
import struct, zlib
ROOT=Path(__file__).resolve().parent.parent

SPRITES={'USC0A0':0,'USC1A0':1,'USRCA0':2,'USROA0':3,'USREA0':4,
         'USHEA0':5,'USORA0':6,'USRIPA0':7,'USSTA0':8,'USLNA0':9,'USDFA0':10,'USGLA0':11,'USLTA0':12,'USCSA0':13,'USARA0':14,'USDSA0':15,'USCTA0':16,'USCUA0':17,'USVDA0':18,'USVRA0':19,'USG0A0':20,'USG1A0':21,'USG2A0':22,'USG3A0':23,'USFSA0':24,'USSMA0':25}

def build(root=ROOT):
 root=Path(root);t=root/'tutnt';out=t/'shaders/sourcefx';out.mkdir(parents=True,exist_ok=True)
 textures=['// Same four native QRUNT63 glyphs as TEXTURES.teleport.',
           'Texture USRUNES, 32, 128 { Patch "QRUNT63", 0, 0 }']
 rune=(root/'tools/source-rune.glsl').read_text()
 defs=[];sprite=rune+(root/'tools/source-sprite.glsl').read_text()
 # Reuse one sprite shader and tiny opaque carriers. Native SOURA0 remains
 # the base image only for the skull/mask; logical sprite sizes stay 512x512.
 (out/'sprite.fp').write_text('// Generated by tools/build_source_materials.py\n'+sprite)
 for name,kind in SPRITES.items():
  if kind<2 or kind==15:
   textures += [f'Sprite {name}, 512, 512 {{ Offset 256, 256 Patch "SOURA0", 0, 0 }}']
  else:
   textures += [f'Sprite {name}, 2, 2 {{ Offset 1, 1 XScale 0.00390625 YScale 0.00390625 Patch "graphics/source-beam/opaque.png", 0, 0 }}']
  defs += [f'Material Sprite "{name}" {{ Shader "shaders/sourcefx/sprite.fp" Texture runeAtlas "USRUNES" Texture stoneAtlas "QROCK3" Texture sourceKind "graphics/source-beam/state{kind:02}.png" }}']
  legacy=out/f'{name.lower()}.fp'
  if legacy.exists():legacy.unlink()
 space=(root/'tools/source-space.glsl').read_text()
 beam=rune+space+(root/'tools/source-beam.glsl').read_text()
 # State data is one opaque texel. Logical wall dimensions remain unchanged;
 # no 1500x512 carrier is uploaded every time the saved defeat phase advances.
 data=t/'graphics/source-beam';data.mkdir(parents=True,exist_ok=True)
 def chunk(tag,body):
  return struct.pack('>I',len(body))+tag+body+struct.pack('>I',zlib.crc32(tag+body)&0xffffffff)
 opaque=b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',2,2,8,6,0,0,0))
 opaque+=chunk(b'IDAT',zlib.compress(bytes([0,255,255,255,255,255,255,255,255])*2))+chunk(b'IEND',b'')
 (data/'opaque.png').write_bytes(opaque)
 for state in range(29):
  png=b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',1,1,8,6,0,0,0))
  png+=chunk(b'IDAT',zlib.compress(bytes([0,state,0,0,255])))+chunk(b'IEND',b'')
  (data/f'state{state:02}.png').write_bytes(png)
 for kind in range(3):
  w,h=(768,64) if kind==0 else (1500,512)
  shader=f'shaders/sourcefx/beam-{0 if kind==0 else 1}.fp'
  for state in range(29):
   name=f'USB{kind}{state}'
   textures += [f'Texture {name}, 1, 1 {{ XScale {1/w:.12f} YScale {1/h:.12f} Patch "graphics/source-beam/state{state:02}.png", 0, 0 }}']
   defs += [f'Material Texture "{name}" {{ Shader "{shader}" Texture runeAtlas "USRUNES" }}']
   # Only these generated legacy shader files belong to this generator.
   legacy=out/f'{name.lower()}.fp'
   if legacy.exists():legacy.unlink()
 for kind in range(2):
  (out/f'beam-{kind}.fp').write_text(f'// Generated by tools/build_source_materials.py\n#define BEAM_KIND {kind}\n'+beam)
 textures += ['Texture USSHIELD, 2, 2 { XScale 0.00390625 YScale 0.00390625 Patch "graphics/source-beam/opaque.png", 0, 0 }']
 (out/'shield.fp').write_text(rune+space+(root/'tools/source-shield.glsl').read_text())
 defs += ['Material Texture "USSHIELD" { Shader "shaders/sourcefx/shield.fp" Texture runeAtlas "USRUNES" }']
 (out/'impact.fp').write_text((root/'tools/source-impact.glsl').read_text())
 defs += ['HardwareShader PostProcess scene { Name "UTNTSourceImpact" Shader "shaders/sourcefx/impact.fp" 330 Uniform vec2 focus Uniform float amount Uniform float progress Uniform float radius Uniform float ending }']
 (t/'TEXTURES.source').write_text('\n'.join(textures)+'\n')
 (t/'GLDEFS.source').write_text('\n'.join(defs)+'\n')

if __name__=='__main__':build()
