"""Assemble engine-readable tables for formats without native includes.

Edit cvarinfo/, keyconf/, language/ and menudef/ modules, then run this tool.
The checked-in root tables also let UZDoom load the source directory directly.
"""
from pathlib import Path
import argparse,json,re
ROOT=Path(__file__).resolve().parents[1]
DIRECTORIES={'GLDEFS':'gldefs','TEXTURES':'textures/definitions','CVARINFO':'cvarinfo','KEYCONF':'keyconf','LANGUAGE':'language','MAPINFO':'mapinfo','MENUDEF':'menudef','MODELDEF':'modeldef','SNDINFO':'sndinfo'}
INCLUDE=re.compile(r'^\s*(?:#include|include|\$include)\s+"([^"]+)"',re.M|re.I)

def render(mod, paths):
    text='// Generated by tools/build_definition_tables.py; edit the referenced modules.\n'
    for name in paths:
        path=(mod/name).resolve()
        if not path.is_relative_to(mod.resolve()) or not path.is_file():
            raise ValueError('Missing or unsafe definition module: '+name)
        text+='\n// @include "'+name+'"\n'+path.read_text(encoding='utf-8-sig').rstrip()+'\n'
    return text.encode('utf-8')

def generate(root=ROOT, check=False):
    root=Path(root);mod=root/'tutnt'
    manifest=json.loads((root/'tools/definition-layout.json').read_text())
    outputs={}
    for entry,paths in manifest.items():
        folder=DIRECTORIES[Path(entry).stem]
        actual={p.relative_to(mod).as_posix() for p in (mod/folder).iterdir() if p.is_file()}
        if set(paths)!=actual or len(paths)!=len(set(paths)):
            raise ValueError('Definition manifest does not match '+folder)
        outputs[entry]=render(mod,paths)
    stale=[n for n,b in outputs.items() if not (mod/n).is_file() or (mod/n).read_bytes().replace(b'\r\n',b'\n')!=b]
    if check and stale:raise ValueError('Stale definition tables; run tools/build_definition_tables.py: '+', '.join(stale))
    if not check:
        for name in stale:(mod/name).write_bytes(outputs[name])
    validate_layout(mod)
    return {'tables':len(outputs),'updated':stale if not check else [],'layout':'ok'}

def validate_layout(mod):
    mod=Path(mod)
    for group,folder in DIRECTORIES.items():
        entry=mod/(group+'.txt')
        if not entry.is_file():raise ValueError('Missing entrypoint: '+entry.name)
        leftovers=[p.name for p in mod.iterdir() if p.is_file() and p.stem.upper()==group and p.name!=entry.name]
        if leftovers:raise ValueError('Definition modules in root: '+', '.join(leftovers))
        if group in ('CVARINFO','KEYCONF','LANGUAGE','MENUDEF'):continue
        visited=set()
        def visit(name,stack=()):
            path=(mod/name).resolve()
            if not path.is_relative_to(mod.resolve()) or not path.is_file():raise ValueError('Missing or unsafe include: '+name)
            if name in stack:raise ValueError('Cyclic include: '+name)
            visited.add(name)
            for target in INCLUDE.findall(path.read_text(encoding='utf-8-sig')):
                if group=='SNDINFO':target=(Path(name).parent/target).as_posix()
                visit(target,stack+(name,))
        visit(entry.name)
        unused={p.relative_to(mod).as_posix() for p in (mod/folder).iterdir() if p.is_file()}-visited
        if unused:raise ValueError('Unreferenced definition modules: '+', '.join(sorted(unused)))

def package_textures(payload):
    """Avoid interpreting source text in textures/ as image assets at runtime."""
    modules={n for n in payload if n.startswith('textures/definitions/')}
    if not modules:return payload
    visited=set()
    def expand(name, stack=()):
        if name in stack:raise ValueError('Cyclic texture include: '+name)
        if name not in payload:raise ValueError('Missing texture include: '+name)
        visited.add(name)
        text=payload[name].decode('utf-8-sig')
        return INCLUDE.sub(lambda m:expand(m[1],stack+(name,)),text)
    text=expand('TEXTURES.txt')
    if modules-visited:raise ValueError('Unreferenced packaged texture definitions')
    result={n:b for n,b in payload.items() if n not in modules}
    result['TEXTURES.txt']=text.encode('utf-8')
    return result

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root',type=Path,default=ROOT)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args();print(json.dumps(generate(args.root,args.check),indent=2))
