class TCOTDBodyArmor : GreenArmor replaces GreenArmor
{
	Default
	{
		Scale 0.833;
		Inventory.Pickupmessage "$IP_BODYARMOR";
		Inventory.Icon "graphics/hud/HUDArmor1.png";
	}

	States
	{
	Spawn:
		ARM1 A -1;
		Stop;
	}
}

class TCOTDSuperArmor : BlueArmor replaces BlueArmor
{
	Default
	{
		Scale 0.833;
		Inventory.Pickupmessage "$IP_SUPERARMOR";
		Inventory.Icon "graphics/hud/HUDArmor2.png";
	}

	States
	{
	Spawn:
		ARM2 A -1;
		Stop;
	}
}
