//Vader Markers//
Class VaderMarker : MapMarker
{
	Default
	{
		//$Category "ZPack Markers"
		+BRIGHT
	}
}

Class YKMarker : VaderMarker
{
	States
	{
	Spawn:
		YSKU B -1;
		Stop;
	}
}

Class BKMarker : VaderMarker
{
	States
	{
	Spawn:
		BSKU B -1;
		Stop;
	}
}

Class RKMarker : VaderMarker
{
	States
	{
	Spawn:
		RSKU B -1;
		Stop;
	}
}

Class SwitchMarker : VaderMarker
{
	States
	{
	Spawn:
		EXCL A -1;
		Stop;
	}
}

Class ExitMarker : VaderMarker
{
	States
	{
	Spawn:
		ARRO A -1;
		Stop;
	}
}