////////////
// THAMUZ //
////////////
Class Thamuz : Cyberdemon
{
	int user_theta;
	int user_Height;
	int user_offset;
	
	Default
	{
	//$Category Monsters (TCOTD2)
	//$Title Thamuz
	Health 3200;
	Speed 5.33333333;
	PainChance 35;
	Mass 2000;
	Scale 1.1;
	Bloodcolor "00 aa 00";
	+LOOKALLAROUND
	+MISSILEEVENMORE
	MinMissileChance 5;
	SeeSound "Thamuz/Idlesight";
	PainSound "Thamuz/Pain";
	DeathSound "Thamuz/death";
	ActiveSound "Thamuz/Idlesight";
	Obituary "$OB_THAM";
	}
	
	States
	{
	Spawn:
		DCYB A 10 NODELAY A_Look;
		Loop;
	See:
		"####" A 1 A_Chase;
		"####" AA 1 A_Chase(null,null,CHF_NOPLAYACTIVE);
		"####" A 0 A_SpawnItemEx("ThamuzGhost",0,0,0,0,0,0,0,SXF_TRANSFERSPRITEFRAME);
		"####" A 1 A_Chase;
		"####" AA 1 A_Chase(null,null,CHF_NOPLAYACTIVE);
		"####" A 0 A_SpawnItemEx("ThamuzGhost",0,0,0,0,0,0,0,SXF_TRANSFERSPRITEFRAME);
		"####" B 1 A_Chase;
		"####" BB 1 A_Chase(null,null,CHF_NOPLAYACTIVE);
		"####" B 0 A_SpawnItemEx("ThamuzGhost",0,0,0,0,0,0,0,SXF_TRANSFERSPRITEFRAME);
		"####" B 1 A_Chase;
		"####" BB 1 A_Chase(null,null,CHF_NOPLAYACTIVE);
		"####" B 0 A_SpawnItemEx("ThamuzGhost",0,0,0,0,0,0,0,SXF_TRANSFERSPRITEFRAME);
		"####" C 1 A_Chase;
		"####" CC 1 A_Chase(null,null,CHF_NOPLAYACTIVE);
		"####" C 0 A_SpawnItemEx("ThamuzGhost",0,0,0,0,0,0,0,SXF_TRANSFERSPRITEFRAME);
		"####" C 1 A_Chase;
		"####" CC 1 A_Chase(null,null,CHF_NOPLAYACTIVE);
		"####" C 0 A_SpawnItemEx("ThamuzGhost",0,0,0,0,0,0,0,SXF_TRANSFERSPRITEFRAME);
		"####" D 1 A_Chase;
		"####" DD 1 A_Chase(null,null,CHF_NOPLAYACTIVE);
		"####" D 0 A_SpawnItemEx("ThamuzGhost",0,0,0,0,0,0,0,SXF_TRANSFERSPRITEFRAME);
		"####" D 1 A_Chase;
		"####" DD 1 A_Chase(null,null,CHF_NOPLAYACTIVE);
		"####" D 0 A_SpawnItemEx("ThamuzGhost",0,0,0,0,0,0,0,SXF_TRANSFERSPRITEFRAME);
		Loop;
	Missile:
		"####" A 0 { user_Height=56; }
		"####" A 0 { user_offset=-25; }
		"####" A 0 A_Jump(160,"Missile2");
		"####" AEE 5 A_FaceTarget;
		"####" F 10 A_SpawnProjectile("DCBMiss1",user_Height,user_offset);
		"####" E 15 A_FaceTarget;
		Goto See;
	Missile2:
		"####" A 0 A_Jump(160,"Missile3");
		"####" A 0 A_SetInvulnerable;
		"####" G 20 A_StartSound("Apocalypse/cast");
	Shock:
		"####" G 0 A_SpawnProjectile("DCBMiss3",50,0,user_theta);
		"####" G 0 { user_theta=user_theta+20; }
		"####" G 0 A_JumpIf(user_theta==360,1);
		Loop;
		"####" G 90 { user_theta=0; }
		"####" G 10 A_UnsetInvulnerable;
		Goto See;
	Missile3:
		"####" AE 3 A_FaceTarget;
		"####" E 4 A_FaceTarget;
		"####" F 4 A_SpawnProjectile("DCBMiss2",user_Height,user_offset);
		"####" E 4 A_FaceTarget;
		"####" F 4 A_SpawnProjectile("DCBMiss2",user_Height,user_offset);
		"####" E 4 A_FaceTarget;
		"####" F 4 A_SpawnProjectile("DCBMiss2",user_Height,user_offset);
		"####" E 4 A_FaceTarget;
		"####" F 4 A_SpawnProjectile("DCBMiss2",user_Height,user_offset);
		"####" E 4 A_FaceTarget;
		"####" F 4 A_SpawnProjectile("DCBMiss2",user_Height,user_offset);
		"####" E 4 A_FaceTarget;
		"####" F 4 A_SpawnProjectile("DCBMiss2",user_Height,user_offset);
		"####" E 4 A_FaceTarget;
		"####" F 4 A_SpawnProjectile("DCBMiss2",user_Height,user_offset);
		"####" E 4 A_FaceTarget;
		"####" F 4 A_SpawnProjectile("DCBMiss2",user_Height,user_offset);
		"####" E 4 A_FaceTarget;
		"####" F 4 A_SpawnProjectile("DCBMiss2",user_Height,user_offset);
		"####" E 4 A_FaceTarget;
		"####" F 4 A_SpawnProjectile("DCBMiss2",user_Height,user_offset);
		Goto See;
	Pain:
		"####" G 2;
		"####" G 2 A_Pain;
		"####" G 0 A_Jump(256,"See");
	Death:
		"####" H 0 A_StartSound("SFX\Explosion1");
		"####" HHHH 5 A_SpawnItemEx("Explosion_Green_A1A",Random(-64,64),Random(-64,64),Random(0,60));
		"####" H 0 A_StartSound("SFX\Explosion1");
		"####" HHH 5 A_SpawnItemEx("Explosion_Green_A1A",Random(-64,64),Random(-64,64),Random(0,60));
		"####" I 7 A_Scream;
		"####" A 0 A_StartSound("Thamuz/death2",CHAN_5);
		"####" JJJJJJJKKKKKKKK 1 A_SpawnProjectile("SFX_Wraith",Random(0,64),0,Random(0,359),2,Random(-16,16));
		"####" A 0 A_SpawnItemEx("Explosion_Green_A1A",Random(-64,64),Random(-64,64),Random(0,60));
		"####" MMMMMMMNNNNNNNOOOOOOO 1 A_SpawnProjectile("SFX_Wraith",Random(0,64),0,Random(0,359),2,Random(-16,16));
		"####" P -1 A_NoBlocking;
		Stop;
	}
}

Class ThamuzGhost : Actor
{
	Default
	{
	Radius 2;
	Height 2;
	Scale 1.1;
	Projectile;
	Alpha 0;
	}
	
	States
	{
	Spawn:
		"####" "#" 3;
		"####" "#" 0 A_SetTranslucent(0.6);
		"####" "#" 3 A_FadeOut;
		Wait;
	}
}

Class DCBMiss1 : Actor
{
	Default
	{
	Radius 12;
	Height 12;
	Speed 6;
	Damage 30;
	Projectile;
	+EXTREMEDEATH
	+SEEKERMISSILE
	+THRUSPECIES
	Species "Horror";
	RenderStyle "Add";
	SeeSound "q2weapon/bfgball";
	DeathSound "q2weapon/bfgballexplo";
	}
	
	States
	{
	Spawn:
		CBTS A 2 BRIGHT LIGHT("ThamuzMissile_1") A_SeekerMissile(10,90);
		TNT1 A 0 A_SpawnItemEx("DCBM1Trail");
		CBTS B 2 BRIGHT LIGHT("ThamuzMissile_1") A_SeekerMissile(10,90);
		TNT1 A 0 A_SpawnItemEx("DCBM1Trail");
		CBTS C 2 BRIGHT LIGHT("ThamuzMissile_1") A_SeekerMissile(10,90);
		TNT1 A 0 A_SpawnItemEx("DCBM1Trail");
		CBTS D 2 BRIGHT LIGHT("ThamuzMissile_1") A_SeekerMissile(10,90);
		TNT1 A 0 A_SpawnItemEx("DCBM1Trail");
		CBTS E 2 BRIGHT LIGHT("ThamuzMissile_1") A_SeekerMissile(10,90);
		TNT1 A 0 A_SpawnItemEx("DCBM1Trail");
		CBTS F 2 BRIGHT LIGHT("ThamuzMissile_1") A_SeekerMissile(10,90);
		TNT1 A 0 A_SpawnItemEx("DCBM1Trail");
		CBTS G 2 BRIGHT LIGHT("ThamuzMissile_1") A_SeekerMissile(10,90);
		TNT1 A 0 A_SpawnItemEx("DCBM1Trail");
		CBTS H 2 BRIGHT LIGHT("ThamuzMissile_1") A_SeekerMissile(10,90);
		TNT1 A 0 A_SpawnItemEx("DCBM1Trail");
		CBTS I 2 BRIGHT LIGHT("ThamuzMissile_1") A_SeekerMissile(10,90);
		TNT1 A 0 A_SpawnItemEx("DCBM1Trail");
		CBTS J 2 BRIGHT LIGHT("ThamuzMissile_1") A_SeekerMissile(10,90);
		TNT1 A 0 A_SpawnItemEx("DCBM1Trail");
		Loop;
	Death:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnItemEx("DCBMiss3Extra",0,0,5,random(-5,5),random(-5,5),random(-5,5),random(1,360));
		CBTS K 2 BRIGHT LIGHT("ThamuzMissile_1X_1") A_Explode(140);
		CBTS L 2 BRIGHT LIGHT("ThamuzMissile_1X_2");
		CBTS M 2 BRIGHT LIGHT("ThamuzMissile_1X_3");
		CBTS N 2 BRIGHT LIGHT("ThamuzMissile_1X_4");
		CBTS O 2 BRIGHT LIGHT("ThamuzMissile_1X_5");
		CBTS P 2 BRIGHT LIGHT("ThamuzMissile_1X_6");
		CBTS Q 2 BRIGHT LIGHT("ThamuzMissile_1X_7");
		CBTS R 2 BRIGHT LIGHT("ThamuzMissile_1X_8");
		CBTS S 2 BRIGHT LIGHT("ThamuzMissile_1X_9");
		CBTS T 2 BRIGHT LIGHT("ThamuzMissile_1X_10");
		CBTS U 2 BRIGHT LIGHT("ThamuzMissile_1X_11");
		CBTS V 2 BRIGHT LIGHT("ThamuzMissile_1X_12");
		CBTS W 2 BRIGHT LIGHT("ThamuzMissile_1X_13");
		Stop;
	}
}

Class DCBM1Trail : Actor
{
	Default
	{
	Radius 1;
	Height 1;
	Scale 0.8;
	Projectile;
	RenderStyle "Add";
	Alpha 0.6;
	+NOCLIP
	}
	
	States
	{
	Spawn:
		TNT1 A 4;
		CBTS LMNOPQRSTUVW 2 BRIGHT A_FadeOut;
		Stop;
	}
}

Class DCBMiss2 : Actor
{
	Default
	{
	Radius 12;
	Height 8;
	Health 5;
	Speed 28;
	Damage 10;
	RenderStyle "Add";
	Projectile;
	+THRUSPECIES
	Species "Horror";
	Translation "160:167=120:127","208:223=120:127";
	SeeSound "q2weapon/rocketlauncherfire";
	DeathSound "q2weapon/rocketexplo";
	}
	
	States
	{
	Spawn:
		THZ4 A 1 BRIGHT LIGHT("ThamuzMissile_2") A_SpawnItemEx("DCBMiss2Trail");
		Loop;
	Death:
		FSFX D 2 BRIGHT LIGHT("ThamuzMissile_2X_1");
		FSFX E 2 BRIGHT LIGHT("ThamuzMissile_2X_2");
		FSFX F 2 BRIGHT LIGHT("ThamuzMissile_2X_3");
		FSFX G 2 BRIGHT LIGHT("ThamuzMissile_2X_4");
		FSFX H 2 BRIGHT LIGHT("ThamuzMissile_2X_5");
		FSFX I 2 BRIGHT LIGHT("ThamuzMissile_2X_6");
		FSFX J 2 BRIGHT LIGHT("ThamuzMissile_2X_7");
		FSFX K 2 BRIGHT LIGHT("ThamuzMissile_2X_8");
		FSFX L 2 BRIGHT LIGHT("ThamuzMissile_2X_9");
		FSFX M 2 BRIGHT LIGHT("ThamuzMissile_2X_10");
		Stop;
	}
}

Class DCBMiss2Trail : DCBM1Trail
{
	Default
	{
	Scale 0.25;
	Alpha 0.4;
	}
	
	States
	{
	Spawn:
		FSFX DEFGHIJKL 1 BRIGHT;
		FSFX M 1 BRIGHT A_FadeOut;
		Wait;
	}
}

Class DCBMiss3 : Actor
{
	Default
	{
	Radius 1;
	Height 1;
	Health 5;
	Speed 8;
	Scale 2;
	RenderStyle "Add";
	Projectile;
	+BLOODLESSIMPACT
	+DONTSPLASH
	+RIPPER
	+THRUSPECIES
	Species "Horror";
	SeeSound "h2necromancer/magiccast";
	}
	
	States
	{
	Spawn:
		TNT1 A 2 A_Gravity;
		Loop;
	Death:
		FSFX NNNOOOPPPQQQRRRSSSTTTNNNOOOPPPQQQRRRSSSTTT 1 BRIGHT LIGHT("ThamuzMissile_3") A_SpawnItemEx("DCBMiss3Extra",0,0,5,random(-5,5),random(-5,5),random(-5,5),random(1,360));
		TNT1 A 0 A_SpawnProjectile("DCBMiss3M",0,0,180);
		Stop;
	}
}

Class DCBMiss3M : Actor
{
	Default
	{
	Radius 10;
	Height 10;
	Speed 28;
	Damage 12;
	Scale 1.3;
	RenderStyle "Add";
	Projectile;
	+FLOORHUGGER
	+THRUSPECIES
	Species "Horror";
	DeathSound "comet/explosion";
	}
	
	States
	{
	Spawn:
		FSFX N 1 BRIGHT LIGHT("ThamuzMissile_3") A_SpawnItemEx("DCBMiss3MG");
		FSFX NNOOOPPPQQQRRRSSSTTT 1 BRIGHT LIGHT("ThamuzMissile_3") A_SpawnItemEx("DCBMiss3Extra");
		Loop;
	Death:
		TNT1 A 0 A_Explode(128,96);
		TNT1 AAAAA 0 A_SpawnItemEx("DCBMiss3Extra");
		FSFX U 3 BRIGHT LIGHT("ThamuzMissile_3X_1");
		FSFX V 3 BRIGHT LIGHT("ThamuzMissile_3X_2");
		FSFX W 3 BRIGHT LIGHT("ThamuzMissile_3X_3");
		Stop;
	}
}

Class DCBMiss3Extra : Actor
{
	Default
	{
	Radius 1;
	Height 1;
	+NOBLOCKMAP
	+NOGRAVITY
	}
	
	States
	{
	Spawn:
		TNT1 AA 0 NODELAY A_SpawnItemEx("DCBMiss3Extra2",0,0,5,random(-5,5),random(-5,5),random(-5,5),random(1,360));
		Stop;
	}
}

Class DCBMiss3Extra2 : DCBMiss3Extra
{
	Default
	{
	Damage 2;
	Scale 0.18;
	RenderStyle "Add";
	Projectile;
	+BLOODLESSIMPACT
	+RIPPER
	+THRUSPECIES
	Species "Horror";
	Translation "168:191=80:82";
	}
	
	States
	{
	Spawn:
		CBTS SS 1 BRIGHT A_Explode(12,32);
		TNT1 A 0 A_Jump(120,1);
		Loop;
		CBTS SSS 1 BRIGHT A_Explode(12,32);
		CBTS S 1 BRIGHT A_FadeOut;
		Wait;
	}
}

Class DCBMiss3MG : Actor
{
	Default
	{
	Radius 1;
	Height 1;
	Scale 0.8;
	Damage 5;
	RenderStyle "Add";
	Alpha 0.6;
	Projectile;
	+RIPPER
	+THRUSPECIES
	Species "Horror";
	}
	
	States
	{
	Spawn:
		TNT1 A 4;
		FSFX NOPQRST 3 BRIGHT;
		Stop;
	}
}

Class Explosion_Green_A1A : Actor
{
	Default
	{
	Radius 1;
	Height 2;
	+CLIENTSIDEONLY
	+NOBLOCKMAP
	+NOGRAVITY
	}
	
	States
	{
	Spawn:
		TNT1 A 1 NODELAY Radius_Quake(8,140,0,16,0);
		TNT1 AAAAAAAAAAAAAAAAAAAA 0 A_SpawnItemEx("GreenEmber_A1A",Random(-16,16),Random(-16,16),Random(0,76),Random(-1,1),Random(-1,1),Random(1,8));
		TNT1 AAAAA 0 A_SpawnItemEx("Fire_Green_A1A",Random(-8,8),Random(-8,8),Random(0,16),Random(-1,1),Random(-1,1),Random(0,8));
		TNT1 AAAAA 0 A_SpawnItemEx("Fire_Green_A1B",Random(-8,8),Random(-8,8),Random(0,16),Random(-1,1),Random(-1,1),Random(0,8));
		TNT1 AAAAA 0 A_SpawnProjectile("SFX_Wraith",Random(0,64),0,Random(0,359),2,Random(-16,16));
		Stop;
	}
}

Class Fire_Green_A1A : Explosion_Green_A1A
{
	Default
	{
	RenderStyle "Add";
	}
	
	States
	{
	Spawn:
		AFGR KJIHGFEDCBA 1 BRIGHT NODELAY A_FadeOut(0.02);
		Wait;
	}
}

Class Fire_Green_A1B : Fire_Green_A1A
{
	States
	{
	Spawn:
		TNT1 A 0 A_SetScale(-Scale.X,Scale.Y);
		Goto Super::Spawn;
	}
}

Class GreenEmber_A1A : Fire_Green_A1A
{
	Default
	{
	Scale 0.05;
	}
	
	States
	{
	Spawn:
		EMGR A 1 BRIGHT A_FadeOut(0.005);
		Loop;
	}
}

Class SFX_Wraith : Actor
{
	Default
	{
	Projectile;
	Speed 8;
	RenderStyle "Add";
	Alpha 0.6;
	Translation "80:111=112:127";
	SeeSound "monster/SprSit";
	}
	
	States
	{
	Spawn:
		WRAI AABB 5 A_FadeOut(0.05);
		Loop;
	}
}

////////////////
// TCHERNOBOG //
////////////////
Class Tchernobog : Thamuz
{
	Default
	{
	//$Title Tchernobog
	Obituary "$OB_TCHE";
	Bloodcolor "aa 00 00";
	}
	
	States
	{
	Spawn:
		TCHR A 10 NODELAY A_Look;
		Loop;
	Missile:
		"####" A 0 { user_Height=64; }
		Goto Super::Missile;
	}
}